{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
{if $act eq 'view'}
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="pull-right"><a class="btn btn-primary" href="?act=add">添加银行卡</a></div>
        <div class="clear"></div>
    </div>
    <div class="nav-main">
        <div class="tab_container">
            <div id="tab1" class="tab_content" style="display: block; ">
                <table class="table">
                    <thead>
                    <tr>
                        <th>开户银行</th>
                        <th>开户人</th>
                        <th>银行卡号</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {foreach from=$bank_list item=bank}
                    <tr>
                        <td>{$bank.bank_name}</td>
                        <td>{$bank.bank_account}</td>
                        <td>{$bank.bank_card}</td>
                        <td>
                            <a href="bank.php?act=edit&id={$bank.id}">编辑</a> |
                            <a href="bank.php?act=delete&id={$bank.id}" onclick="return confirm_delete();">删除</a>
                        </td>
                    </tr>
                    {/foreach}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function confirm_delete() {
        if(confirm("您确定要删除该银行卡？")) {
            return true;
        } else {
            return false;
        }
    }
</script>
<!-- END content -->
{/if}

{if $act eq 'add' or $act eq 'edit'}
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{if $act eq 'add'}添加{else}修改{/if}银行卡</h5>
        <div class="clear"></div>
    </div>
    <div class="nav-main">
        <form id="navForm" name="navAddForm" method="post">
            <fieldset>
                <p>
                    <label class="l-title">开户银行：</label>
                    <input class="text-input w300" type="text" id="bank_name" name="bank_name" placeholder="请输入开户银行" {if $act eq 'edit'}value="{$bank.bank_name}"{/if}>
                </p>
                <p>
                    <label class="l-title">开户人：</label>
                    <input class="text-input w300" type="text" id="bank_account" name="bank_account" placeholder="请输入开户人" {if $act eq 'edit'}value="{$bank.bank_account}"{/if}>
                </p>
                <p>
                    <label class="l-title">银行卡号：</label>
                    <input class="text-input w300" type="text" id="bank_card" name="bank_card" placeholder="请输入银行卡号" {if $act eq 'edit'}value="{$bank.bank_card}"{/if}>
                </p>
                <p>
                    <label class="l-title"></label>
                    {if $act eq 'edit'}
                    <input type="hidden" name="eid" value="{$bank.id}"/>
                    {/if}
                    <input type="hidden" name="opera" value="{$act}"/>
                    <button class="btn btn-primary" type="submit">{if $act eq 'add'}添加{else}修改{/if}</button>
                    &nbsp;<a href="bank.php" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
    </div>
</div>
{/if}
{include file="library/footer.lbi"}
</body>
</html>
