{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}

<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="adminGroup-main">
        {if $act eq 'view'}
        <div class="article-main-header">
            <form action="" method="get" />
            <fieldset>
                <p>
                <div class="pull-left">
                    显示
                    <select name="count" class="w75">
                        <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                        <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                        <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                        <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                    </select>
                    项结果
                </div>
                <div class="pull-right">
                    <label>提现编号：</label>
                    <input class="text-input w150" type="text" id="small-input" name="apply_sn" value="{$apply_sn}">&nbsp;
                    <label>会员编号：</label>
                    <input class="text-input w150" type="text" id="small-input" name="account" value="{$account}">&nbsp;
                    <label>提现状态：</label>
                    <select name="status">
                        <option value="-1">全部</option>
                        <option value="0" {if $status eq 0}selected="selected"{/if}>待处理</option>
                        <option value="1" {if $status eq 1}selected="selected"{/if}>已处理</option>
                    </select><br/><br/>
                    <label>起止时间：</label>
                    <input class="text-input w150" type="text" id="begin_time" name="begin_time" value="{$begin_time}">&nbsp;
                    至
                    <input class="text-input w150" type="text" id="end_time" name="end_time" value="{$end_time}">&nbsp;
                    <button type="submit" class="btn btn-default">搜索</button>
                </div>
                </p>
            </fieldset>
            </form>
            <div class="clear"></div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>申请编号</th>
                <th>会员账号</th>
                <th>提现金额</th>
                <th>手续费</th>
                <th>申请时间</th>
                <th>备注</th>
                <th>状态</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$withdraw_list item=withdraw}
            <tr>
                <td>{$withdraw.apply_sn}</td>
                <td>{$withdraw.account}</td>
                <td>{$withdraw.amount}</td>
                <td>{$withdraw.fee}</td>
                <td>{date('Y-m-d H:i:s', $withdraw.apply_time)}</td>
                <td>{$withdraw.remark}</td>
                <td>{$LANG.withdraw["status_{$withdraw.status}"]}</td>
                <td>
                    {$withdraw.operation}
                </td>
            </tr>
            {/foreach}
            <tr>
                <td colspan="8">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&keyword={$keyword}&count={$count}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&keyword={$keyword}&count={$count}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&keyword={$keyword}&count={$count}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&keyword={$keyword}&count={$count}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&keyword={$keyword}&count={$count}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
        <script type="text/javascript" src="laydate/laydate.js"></script>
        <script type="text/javascript">
            var start = {
                elem: '#begin_time',
                format: 'YYYY-MM-DD',
                max: '9999-12-31 23:59:59', //最大日期
                istime: false,
                istoday: true,
                choose: function(datas){
                    end.min = datas; //开始日选好后，重置结束日的最小日期
                    end.start = datas //将结束日的初始值设定为开始日
                    end.click;
                }
            };

            var end = {
                elem: '#end_time',
                format: 'YYYY-MM-DD',
                max: '9999-12-31 23:59:59',
                istime: false,
                istoday: true,
                choose: function(datas){
                    start.max = datas; //结束日选好后，重置开始日的最大日期
                }
            };

            laydate(start);
            laydate(end);
        </script>
        {/if}

        <!-- 提现处理 -->
        {if $act eq 'edit'}
        <form method="post">
            <fieldset>
                <p>
                    <label class="l-title">会员账号：</label>
                    {$withdraw.account}
                </p>
                <p>
                    <label class="l-title">提现金额：</label>
                    {$withdraw.amount}
                </p>
                <p>
                    <label class="l-title">手续费：</label>
                    {$withdraw.fee}
                </p>
                <p>
                    <label class="l-title">申请时间：</label>
                    {date('Y-m-d H:i:s', $withdraw.apply_time)}
                </p>
                <p>
                    <label class="l-title">备注：</label>
                    {$withdraw.remark}
                </p>
                <p>
                    <label class="l-title">汇入账户：</label>
                    开户行：{$withdraw.bank_name}
                    开户人：{$withdraw.bank_account}
                    银行卡号：{$withdraw.bank_card}
                </p>
                <p>
                    <label class="l-title">备注：</label>
                    <input class="text-input w300" type="text" id="remark" name="remark" placeholder="请输入备注" value="">
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="edit"/>
                    <input type="hidden" name="ewithdraw_sn" value="{$withdraw.apply_sn}">
                    <button class="btn btn-primary" type="submit">设为已处理</button> &nbsp;<a href="withdraw.php" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
        {/if}
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>