{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="adpos-main">
        <form id="adpos-form" name="adpos-form" method="post" onsubmit="return do_submit();">
            <fieldset>
                <p class="clear">
                    <label class="l-title">广告位置名称:</label>
                    <input class="text-input w300" type="text" id="pos_name" name="pos_name" placeholder="请输入广告位置名称"/>
                    <span class="error-input" id="pos_name-error">{if isset($error.pos_name)}{$error.pos_name}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">广告图片宽度:</label>
                    <input class="text-input w300" type="text" id="width" name="width" placeholder="请输入广告图片宽度"/>
                    <span class="error-input" id="width-error">{if isset($error.width)}{$error.width}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">广告图片高度:</label>
                    <input class="text-input w300" type="text" id="height" name="height" placeholder="请输入广告高度" value=""/>
                    <span class="error-input" id="height-error">{if isset($error.height)}{$error.height}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">广告图片展示数量:</label>
                    <input class="text-input w300" type="number" id="number" name="number" placeholder="请输入广告图片展示数量" value="1"/>
                    <span class="error-input" id="number-error">{if isset($error.number)}{$error.number}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">广告代码:</label>
                    <textarea name="code" id="code" placeholder="请输入广告代码" class="w300" rows="10"></textarea>
                    <span class="error-input" id="code-error">{if isset($error.code)}{$error.code}{/if}</span>
                </p>
                <p>
                    <label class="l-title"></label>
                    <a class="btn btn-primary" id="submit-btn" href="javascript:;">
                        新增<img src="images/btn_loading.gif" class="btn-loading-img"/>
                    </a>&nbsp;
                    <input type="hidden" name="opera" value="add"/>
                    <a href="javascript:history.go(-1);" class="btn btn-primary">返回</a>
                </p>                
            </fieldset>
        </form> 
    </div>
</div>
<div id="mask"></div>
<script type="text/javascript">
$(function() {
    $("#submit-btn").click(do_submit);
});
/**
* 这个解决方案可以作为Ajax提交表单的模板
* 1、form的提交操作托管给do_submit处理;
* 2、Ajax操作分为两部分，第一部分do_submit作为提交前的参数验证，第二部分do_resposne作为返回代码的处理;
* 3、仅支持post方式提交表单;
* 4、需要在提交按钮加入提交中的加载图片，以及遮罩层代码<div id="mask"></div>
**/
function do_submit() {
    //参数校验
    var pos_name = $("#pos_name").val().trim();
    var height = $("#height").val();
    var width = $("#width").val();
    var number = $("#number").val().trim();
    var code = $("#code").val();
    var flag = true;

    if(pos_name == "") {
        $("#pos_name-error").text("-请输入广告位置名称");
        flag = false;
    } else {
        $("#pos_name-error").text("");
    }

    if(height == "") {
        $("#height-error").text("-请输入广告图片高度");
        flag = false;
    } else {
        $("#height-error").text("");
    }

    if(width == "") {
        $("#width-error").text("-请输入广告图片宽度");
        flag = false;
    } else {
        $("#width-error").text("");
    }

    number = parseInt(number);

    if(isNaN(number) || number < 0)
    {
        $("#number-error").text("-请输入广告图片展示数量");
        flag = false;
    } else {
        $("#number-error").text("");
    }

    if(flag) {
        flag = true;
        //启用过渡效果
        $(".btn-loading-img").show();
        $("#submit-btn").addClass("btn-disabled");
        $("#mask").show();

        var params = { "opera":"add", "pos_name":pos_name, "height":height, "width":width, "code":code, "number":number };
        var url = "adpos.php";
        $.post(url, params, do_response, "json");
    }

    return flag;
}

function do_response(result) {
    //关闭过渡效果
    $(".btn-loading-img").hide();
    $("#submit-btn").removeClass("btn-disabled");
    $("#mask").hide();
    //处理返回结果
    if(result.error == 0) {
        alert(result.msg);
        document.forms['adpos-form'].reset();
    } else {
        if(result.msg != "") {
            alert(result.msg);
        }

        if(result.errmsg.length) {
            for(var id in result.errmsg) {
                $("#"+id+"-error").text(result.errmsg[id]);
            }
        }
    }
}
/*----------------  Ajax end ---------------------*/
</script>
<!-- END content -->
{include file="library/footer.lbi"}
</body>
</html>
