{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">编辑资讯分类</h5>
        <div class="clear"></div>
    </div>
    <div class="article-main">
        <form id="articleCatForm" name="articleCatEditForm" method="post">
            <fieldset>
                <p>
                    <label class="l-title">资讯分类名称：</label>
                    <input class="text-input w300" type="text" id="articleCatName" name="articleCatName" placeholder="请输入资讯分类名称" maxlength="32" value="{$section.section_name}" />
                </p>
                <p>
                    <label class="l-title">父级分类：</label>
                    <select name="parentId" class="w150">
                        <option value="0">顶级分类</option>
                        {foreach from=$sectionList item=s}
                        <option value="{$s.id}" {if $section.parent_id eq $s.id}selected="selected"{/if}>{$s.section_name}</option>
                        {/foreach}
                    </select>
                </p>
                <p>
                    <label class="l-title">栏目关键字：</label>
                    <input class="text-input w300" type="text" id="keywords" name="keywords"  placeholder='请输入分类关键字，多个关键字以英文逗号","隔开' value="{$section.keywords}" />
                </p>
                <p>
                    <label class="l-title">栏目描述：</label>
                    <textarea class="w300" id="description" name="description" maxlength="140" rows="5">{$section.description}</textarea>
                </p>
                <p>
                    <label class="l-title">封面：</label>
                    <input type="button" class="text-input" id="select-image" value="请选择栏目封面" style="cursor:pointer">
<!--                                        <div id="show-image" style="width: 187px; height: 140px; display: inline-block">-->
                    <!--                    </div>-->
                    <input type="hidden" class="" name="img" id="img" value="{$section.original}"/>
                </p>
                <p>
                    <label class="l-title"></label>
                    {if $section.original eq ''}
                    <img id="show-image" alt="未选择图片" src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image">
                    {else}
                    <img id="show-image" alt="" src="{$section.original}" width="{if $configs.sthumb_width neq ''}{$configs.sthumb_width}px{else}75px{/if}" height="{if $configs.sthumb_height neq ''}{$configs.sthumb_height}px{else}75px{/if}"/>
                    {/if}
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="edit" />
                    <input type="hidden" name="id" value="{$section.id}" />
                    <button class="btn btn-primary" type="submit">提交</button> &nbsp;<a href="section.php.php" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="../plugins/kindeditor/plugins/code/prettify.css"/>
<link rel="stylesheet" type="text/css" href="../plugins/kindeditor/themes/default/default.css"/>
<script type="text/javascript" src="../plugins/kindeditor/kindeditor-all-min.js"></script>
<script type="text/javascript">
    KindEditor.ready(function(K)
    {
        var editor = K.editor({
            allowFileManager : true,
            uploadJson : '../plugins/kindeditor/section_upload_json.php',
            fileManagerJson : '../plugins/kindeditor/file_manager_json.php'
        });
        K('#select-image').click(function() {
            editor.loadPlugin('image', function() {
                editor.plugin.imageDialog({
                    imageUrl : '',
                    clickFn : function(url, title, width, height, border, align) {
                        if( !width ) {
                            width = '{$configs.sthumb_width}';
                            width = (width == '') ? '75px' : width + 'px'
                        }
                        if( !height ) {
                            height = '{$configs.sthumb_height}';
                            height = (height == '') ? '75px' : height + 'px'
                        }

                        K('#img').val(url);
//                        K('#select-image').val('');
                        K('#show-image').attr('src', url);
                        K('#show-image').css('width', width);
                        K('#show-image').css('height', height);                        K('#show-image').css('display', 'block');
//                        K('#show-image').css('display', 'block');
                        editor.hideDialog();
                    }
                });
            });
        });
//    prettyPrint();
    });
</script>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>