{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}

<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="adminGroup-main">
        <form method="post">
            <fieldset>
                <p>
                    <label class="l-title">月份：</label>
                    <input class="text-input w150" type="text" id="settle_time" name="settle_time" value="">
                </p>

                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="level_up"/>
                    <button class="btn btn-primary" type="submit">立即升级</button> &nbsp;<a href="reward.php" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
    </div>
</div>
<!-- END content -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script type="text/javascript">
    laydate.render({
        elem: '#settle_time',
        type: 'month'
    });
</script>

{include file="library/footer.lbi"}
</body>
</html>