{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="ad-main">
        <form id="ad-form" name="ad-form" method="post" onsubmit="return do_submit();">
            <fieldset>
                <p class="clear">
                    <label class="l-title">客服账号:</label>
                    <input class="text-input w300" type="text" id="kf_account" name="kf_account" placeholder="请输入客服账号"/>
                    @{$config.wechat_account}
                    <span class="error-input" id="kf_account-error"></span>
                </p>
                <p class="clear">
                    <label class="l-title">客服昵称:</label>
                    <input class="text-input w300" type="text" id="nickname" name="nickname" placeholder="请输入客服昵称"/>
                    <span class="error-input" id="nickname-error"></span>
                </p>
                <p class="clear">
                    <label class="l-title">客服密码:</label>
                    <input class="text-input w300" type="password" id="password" name="password" placeholder="请输入客服密码"/>
                    <span class="error-input" id="password-error"></span>
                </p>
                <p>
                    <label class="l-title"></label>
                    <a class="btn btn-primary" id="submit-btn" href="javascript:;">
                        新增<img src="images/btn_loading.gif" class="btn-loading-img"/>
                    </a>&nbsp;
                    <input type="hidden" name="opera" value="add"/>
                    <a href="javascript:history.go(-1);" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
    </div>
</div>
<div id="mask"></div>
<script type="text/javascript">
    $(function() {
        $("#submit-btn").click(do_submit);
    });
    /**
     * 这个解决方案可以作为Ajax提交表单的模板
     * 1、form的提交操作托管给do_submit处理;
     * 2、Ajax操作分为两部分，第一部分do_submit作为提交前的参数验证，第二部分do_resposne作为返回代码的处理;
     * 3、仅支持post方式提交表单;
     * 4、需要在提交按钮加入提交中的加载图片，以及遮罩层代码<div id="mask"></div>
     **/
    function do_submit() {
        //参数校验
        var flag = true;
        var kf_account = $("#kf_account").val().trim();
        var password = $("#password").val().trim();
        var nickname = $("#nickname").val().trim();

        if(kf_account == "") {
            $("#kf_account-error").text("-请输入客服账号");
            flag = false;
        } else {
            $("#kf_account-error").text("");
        }

        if(nickname == "") {
            $("#nickname-error").text("-请输入客服昵称");
            flag = false;
        } else {
            $("#nickname-error").text("");
        }

        if(password == "") {
            $("#password-error").text("-请输入客服密码");
            flag = false;
        } else {
            $("#password-error").text("");
        }

        if(flag) {
            flag = true;
            //启用过渡效果
            $(".btn-loading-img").show();
            $("#submit-btn").addClass("btn-disabled");
            $("#mask").show();

            var params = { "opera":"add", "kf_account":kf_account, "password":password, "nickname":nickname };
            var url = "wechat_kf.php";
            $.post(url, params, do_response, "json");
        }

        return flag;
    }

    function do_response(result) {
        //关闭过渡效果
        $(".btn-loading-img").hide();
        $("#submit-btn").removeClass("btn-disabled");
        $("#mask").hide();
        //处理返回结果
        if(result.error == 0) {
            alert(result.msg);
            document.forms['ad-form'].reset();
        } else {
            if(result.msg != "") {
                alert(result.msg);
            }

            if(result.errmsg.length) {
                for(var id in result.errmsg) {
                    $("#"+id+"-error").text(result.errmsg[id]);
                }
            }
        }
    }
    /*----------------  Ajax end ---------------------*/
</script>
<!-- END content -->
{include file="library/footer.lbi"}
</body>
</html>