<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>收货地址列表</em></h1>
    <a href="address.php?act=add" class="edit">新增</a>
</header>
<!-- 收货地址列表 -->
<section id="address-list">
    <div class="address-list">
        {if $address_list}
        {foreach from=$address_list item=address}
        <div class="address_item">
            <div class="detail">
                <p class="a-name">收货人：{$address.consignee}<span class="a-phone">{$address.mobile}</span></p>
                <p class="a-address">收货地址：{$address.detail_address}</p>
                <div class="clear tags">
                    {if $address.is_default}<span>默认地址</span>{/if}
                    <a class="garbage" href="address.php?act=edit&id={$address.id}"></a>
                    <a class="garbage address-del" href="javascript:delete_address_confirm({$address.id});"></a>
                </div>
            </div>
            <div class="bottom_line"></div>
        </div>
        {/foreach}
        {else}
        您尚未添加任何地址
        {/if}
    </div>
</section>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="confirm_dialog" style="display: none;">
        <p>确定要删除该地址吗？</p>
        <ul class="cd-buttons">
            <li><a id="dialog_confirm_btn" href="javascript:void(0);">非删不可</a></li>
            <li><a href="javascript:close_operation_dialog('confirm_dialog');">说说而已</a></li>
        </ul>
        <a href="javascript:close_operation_dialog('confirm_dialog');" class="cd-popup-close img-replace">X</a>
    </div>

    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a id="dialog_close_btn" href="javascript:close_message_dialog();">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" id="dialog_close" class="cd-popup-close img-replace">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    var id = 0;

    $(function(){
        var need_refresh = window.localStorage.getItem("need_refresh");
        if(need_refresh == 1) {
            window.localStorage.setItem("need_refresh", 0);
            window.location.reload();
        }
    });

    function delete_address_confirm(eid) {
        id = eid;
        show_operation_dialog("confirm_dialog");
        $("#dialog_confirm_btn").click(function() {
            close_operation_dialog("confirm_dialog");
            delete_address(id);
        });
    }

    function delete_address(id) {
        id = parseInt(id);
        var msg = "";

        if(isNaN(id) || id <= 0) {
            msg += "-参数错误<br/>";
        }

        if(msg == "") {
            var url = "address.php";
            var data = { "opera":"delete", "eid":id };

            show_mask();
            $.post(url, data, delete_address_handler, "json");
        } else {
            show_message_dialog(msg);
        }
    }

    function delete_address_handler(response) {
        hide_mask();

        show_message_dialog(response.msg);
        if(response.error == 0) {
            $("#dialog_close_btn").attr("href", "javascript:window.location.reload();");
            $("#dialog_close").click(function() {
                window.location.reload();
            });
        }
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").html(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function show_operation_dialog(id) {
        if(id == undefined) {
            id = "dialog";
        }
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#"+id).show();
    }

    function close_operation_dialog(id) {
        if(id == undefined) {
            id = "dialog";
        }
        $(".cd-popup").removeClass("is-visible");
        $("#"+id).hide();
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }
</script>
</body>
</html>
