{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我的银行卡</em></h1>
    <a href="bank.php?act=add" class="edit">添加</a>
</header>
{/block}
{block name="content"}
<!-- 银行卡列表 -->
<section class="bank">
    <div class="bank-list">
        <ul>
            {foreach from=$bank_list item=bank}
            <li class="bank-list-item">
                <div class="bank-title">
                    <div class="fl">{$bank.bank_name}</div>
                    <div class="fr">尾号{substr($bank.bank_card, -4)}<span>储蓄卡</span></div>
                </div>
                <div class="bank-con">
                    <div class="bank-item">
                        <span class="info">持卡人姓名：***{mb_substr($bank.bank_account, -1)}</span>
                        <a href="bank.php?act=edit&id={$bank.id}" class="font-gray fr">修改</a>
                    </div>
                    <div class="bank-item">
                        <span class="info">手机号：{substr($bank.mobile, 0, 3)}****{substr($bank.mobile, -4)}</span>
                        <a href="javascript:delete_bank_confirm({$bank.id});" class="font-gray fr">删除</a>
                    </div>
                </div>
            </li>
            {/foreach}
            <li class="quick-add">
                <a class="quick-add-item" href="bank.php?act=add">
                    <span class="icon bg">+</span>
                    添加银行卡
                </a>
            </li>
        </ul>
    </div>
</section>
<div style="height: 2.2rem;"></div>

<script type="text/javascript">
    var id = 0;
    $(function(){
        $(".bank-list-item").click(function(){
            $(this).addClass("hover").find(".font-gray").show();
            $(this).siblings().removeClass("hover").find(".font-gray").hide();
        })

        $(".font-gray").each(function(i, e){
           $(e).hide();
        });
    });

    function delete_bank_confirm(eid) {
        id = eid;
        show_operation_dialog("confirm_dialog");
        $("#dialog_confirm_btn").click(function() {
            close_operation_dialog("confirm_dialog");
            delete_bank(id);
        });
    }

    function delete_bank(id) {
        id = parseInt(id);
        var msg = "";

        if(isNaN(id) || id <= 0) {
            msg += "-参数错误<br/>";
        }

        if(msg == "") {
            var url = "bank.php";
            var data = { "opera":"delete", "eid":id };

            show_mask();
            $.post(url, data, delete_bank_handler, "json");
        } else {
            show_message_dialog(msg);
        }
    }

    function delete_bank_handler(response) {
        hide_mask();

        show_message_dialog(response.msg);
        if(response.error == 0) {
            $("#dialog_close_btn").attr("href", "javascript:window.location.reload();");
            $("#dialog_close").click(function() {
                window.location.reload();
            });
        }
    }
</script>
{/block}
{block name="footer"}
{/block}