{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <div class="h_label">购物车</div>
</header>
{/block}
{block name="content"}
<!-- 购物车列表 -->
{if $product_list}
<section class="cart">
    {foreach from=$product_list item=cart}
    <div class="block">
        <div class="cart_list">
            <div class="cart_item">
                <input type="checkbox" class="fl c_checkbox" id="cart_{$cart.c_id}" onclick="select_product({$cart.c_id}, this.checked);">
                <img src="{$cart.img|build_url}" class="fl pro_pic">
                <div class="detail">
                    <p class="fl prd_tit"><a href="#">{$cart.name}</a></p>
                    <p class="fr prd_price">￥{sprintf("%.2f", $cart.price)}</p>
                    <p class="fl prd_tit">{$cart.attributes}</p>
                    <div class="clear tags">
                        <!-- 数量开始 -->
                        <section class="quantity">
                            <div class="number_con">
                                <span class="minus {if $cart.number gt 1}on{/if}" id="minus_{$cart.c_id}" onclick="minus({$cart.c_id})">-</span>
                                <div class="input"><input type="tel" value="{$cart.number}" id="product_{$cart.c_id}" readonly="true"/></div>
                                <span class="plus on" id="plus_{$cart.c_id}" onclick="plus({$cart.c_id})">+</span>
                            </div>
                        </section>
                        <a class="garbage" href="javascript:delete_cart_item({$cart.c_id});" style="display: inline;"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {/foreach}
</section>

<div style="height: 3.5rem;"></div>
<!-- 去结算 -->
<footer class="total_result">
    <div class="fl ">
        <input type="checkbox" class="c_checkbox" id="cart_check_all" style="">
        <span>全选</span>
    </div>

    <div class="fr">
        <a style="border:.1rem solid red;" class="c_btn payBtn" id="check_out_btn" href="javascript:void(0);">去结算(<span id="cart_quantity">{$total_number}</span>)</a>
    </div>
    <div class="fr totalPrice">
        <span>商品金额总计</span>
        <p id="cart_price">
            <span id="total_amount">￥{sprintf("%.2f", $total_amount)}</span>
        </p>
    </div>
</footer>
{else}
<div class="block">
    <div class="empty-con">
        <span class="icon">&#xe602;</span>
        <span class="empty-tips">您的购物车空空如也!</span>
            <span class="empty-btn">
                <a href="index.php" class="btn">去逛逛</a>
            </span>
    </div>
</div>
{/if}
<script type="text/javascript">
    var total_amount = {$total_amount};
    var total_integral = {$total_integral};
    var cart = {$cart_json};
    var select_cid = 0;

    //删除购物车
    function delete_cart_item(cid) {
        $("#delete_confirm_btn").bind("click", function() { remove_from_cart(cid); });
        show_operation_dialog();
        $("#confirm-message").text("您确定要移除该产品?");
        $("#dialog_confirm_btn").text("非删不可");
        $("#dialog_confirm_cancel").text("留你一命");
        select_cid = cid;

        $("#dialog_confirm_btn").click(function(){
            remove_from_cart(select_cid);
        });
    }

    function remove_from_cart(cid) {
        cid = parseInt(cid);

        if(isNaN(cid) || cid <= 0) {
            show_message_dialog("无效的id");
            return false;
        }
        console.info(cid);
        var url = "cart.php";
        data = { "opera":"delete", "cid":cid };

        show_mask();
        $.post(url, data, remove_from_cart_handler, "json");
    }

    function remove_from_cart_handler(response) {
        hide_mask();
        if(response.error == 0) {
            window.location.reload();
        } else {
            show_message_dialog(response.msg);
        }
    }

    // 加减操作
    function enable_operation(mode, cid, flag) {
        if(flag) {
            $("#" + mode + "_" + cid).addClass("on");
        } else {
            $("#" + mode + "_" + cid).removeClass("on");
        }
    }

    function plus(cid) {
        var buy_num = $("#product_"+cid).val();
        buy_num = parseInt(buy_num);

        if(isNaN(buy_num) || buy_num <= 0) {
            buy_num = 0;
        }

        buy_num++;

        $("#product_"+cid).val(buy_num);

        check_inventory(cid, buy_num);
        caculate_fee();
    }

    function minus(cid) {
        var buy_num = $("#product_"+cid).val();
        buy_num = parseInt(buy_num);

        if(isNaN(buy_num) || buy_num <= 1) {
            buy_num = 2;
        }

        buy_num--;

        $("#product_"+cid).val(buy_num);

        check_inventory(cid, buy_num);
        caculate_fee();
    }

    function check_inventory(cid, buy_num) {
        if(cart[cid].inventory < buy_num) {
            buy_num = cart[cid].inventory;
            $("#product_"+cid).val(cart[cid].inventory);
            enable_operation("plus", cid, false);
        } else {
            enable_operation("plus", cid, true);
        }

        if(buy_num == 1) {
            enable_operation("minus", cid, false);
        } else {
            enable_operation("minus", cid, true);
        }

        cart[cid].number = buy_num;
    }

    //选择产品
    function select_product(c_id, flag) {
        if(cart[c_id] != undefined) {
            cart[c_id].checked = flag;
            document.getElementById("cart_"+c_id).checked = flag;
        }

        caculate_fee();
    }

    //更改复选框状态
    function set_checkbox_checked(id, flag) {
        document.getElementById(id).checked = flag;
    }

    //计算购物车费用
    function caculate_fee() {
        var price_amount = 0;
        var integral_amount = 0;
        var buy_num = 0;

        for(var i in cart) {
            if(cart[i].checked) {
                price_amount += cart[i].price * cart[i].number;
                integral_amount += cart[i].integral * cart[i].integral;
                buy_num += cart[i].number;
            }
        }

        $("#total_amount").text("￥"+price_amount.toFixed(2));
        $("#cart_quantity").text(buy_num);
    }

    //去结算
    function check_out() {
        var url = "cart.php";
        var data = { "opera":"checkout", "cart":cart };
        var buy_num = 0;

        for (var i in cart) {
            if (cart[i].checked) {
                buy_num += cart[i].number;
            }
        }

        if(buy_num > 0) {
            show_mask();
            $.post(url, data, check_out_handler, "json");
        } else {
            console.info("show_message_dialog");
            show_message_dialog("请选择要购买的产品");
        }
    }

    function check_out_handler(response) {
        if(response.error == 0) {
            window.location.href = "checkout.php";
        } else {
            show_message_dialog(response.msg);
            if(response.refresh) {
                $("#message_dialog_close").bind("click", function() { window.location.reload(); });
                $("#message_dialog_btn").bind("click", function() { window.location.reload(); });
            }
        }
    }

    function select_all_product(flag) {
        for(var i in cart) {
            cart[i].checked = flag;
            select_product(i, flag);
        }
    }

    $(function(){
        $("#check_out_btn").bind("click", function() { check_out(); });
        $("#cart_check_all").bind("click", function() { select_all_product(this.checked); });

        var flag = true;
        for(var i in cart) {
            select_product(i, cart[i].checked);
            if(!cart[i].checked) {
                flag = false;
            }
        }

        set_checkbox_checked("cart_check_all", flag);
    });
</script>
{/block}
{block name="footer"}
{/block}