{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>确认订单</em></h1>
</header>
{/block}
{block name="content"}
<!-- 确定订单 -->
<section class="checkout-con">
    <!-- 订单产品详情 -->
    <section class="orders">
        <div class="w_panel border_lr order_main border_top rarrow">
            <h4 class="h_title">
               <i class="icon">&#xe610;</i>&nbsp;{$config.site_name}
            </h4>
        </div>
        <div class="border_lr trans_div order_action_block border_bottom">
            <div>
                <div>
                    <ul class="product_ul">
                        {foreach from=$product_list item=product}
                        <li>
                            <div class="box">
                                <div class="product_cover">
                                    <img width="100%" src="{$product.img|build_url}">
                                </div>
                                <div class="product_info cr_2">
                                    <p class="product_name">{$product.name}</p>
                                    <p class="product_name">{$product.attributes}</p>
                                    <p>
                                        {if $product.integral gt 0}
                                        <span class="red_money">{sprintf("%.2f", $product.integral)}积分</span>
                                        {else}
                                        <span class="red_money">￥{sprintf("%.2f", $product.price)}</span>
                                        {/if}
                                        <span>&nbsp;×{$product.number}</span>
                                    </p>
                                </div>
                            </div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
                <hr color="#E5E5E5" class="line_l" size="1">
            </div>
        </div>
    </section>
    {if ($user_info.reward gt 0 or $user_info.balance gt 0) and $total_amount gt 0}
    <section class="preferential border_bottom">
        <ul class="preferential-list">
            {if $user_info.reward gt 0}
            <li>
                可用奖金
                {if $user_info.reward>$total_amount}
                {$total_amount}
                {assign var=reward value=$total_amount}
                {else}
                {$user_info.reward}
                {assign var=reward value=$user_info.reward}
                {/if}
                元
                <input name="use_reward" id="use_reward" type="checkbox" class="fr c_checkbox" value="use_reward"/>
            </li>
            {/if}
            {if $user_info.balance gt 0}
            <li>
                可用余额
                {if $user_info.balance>$total_amount}{$total_amount}{else}{$user_info.balance}{/if}
                元
                <input name="use_balance" id="use_balance" type="checkbox" class="fr c_checkbox" value="use_balance"/>
            </li>
            {/if}
        </ul>
    </section>
    {/if}

    <div class="edit-address preferential border_bottom">
        <div class="w_panel border_lr order_main border_top rarrow">
            <h4 class="h_title">
                收货信息
            </h4>
        </div>
        <div class="single_line_div leavemessage">
            <span><input name="consignee" id="consignee" placeholder="收货人" value="" data-original-length="0" type="text"></span>
        </div>
        <div class="single_line_div leavemessage">
            <span><input name="zipcode" id="zipcode" placeholder="邮政编码" value="" data-original-length="0" type="text"></span>
        </div>
        <div class="single_line_div leavemessage">
            <span><input name="address" id="address" placeholder="收货地址" value="" data-original-length="0" type="text"></span>
        </div>
        <div class="single_line_div leavemessage">
            <span><input name="phone" id="phone" placeholder="联系电话" value="" data-original-length="0" type="text"></span>
        </div>
    </div>

    <div class="paydetail" style="background: #fff;">
        <ul>
            <li>支付方式：
                <span><em class="icon" style="padding-right: 5px;">&#xe60f;</em>微信支付</span>
            </li>
        </ul>
    </div>

    <div style="height: 60px;"></div>
    <input type="hidden" name="payment_id" id="payment_id" value="1"/>
    <!-- 提交订单 -->
    <section class="order-submit">
        <div class="order_review">
            <div style="float:left;width:69%;padding:5px 0;line-height:41px;">
                <div style="float:left;">
                    <span style="font-size:12px;display:inline-block;color:#464646;">共{$total_number}件商品，总额(含运费)</span>
                    <a class="red_money" style="margin:0 0 0 5px;font-size:14px;display:inline-block;" id="order_amount">￥{sprintf("%.2f", $total_amount)} </a>
                    <br>
                </div>
            </div>
            <input type="hidden" name="payment" id="payment" value=""/>
            <a href="javascript:void(0);" id="submit_order_btn" class="yellow_btn">提交订单</a>
        </div>
    </section>
</section>

<script type="text/javascript">
    var total_amount = {$total_amount};
    var total_product_amount = {$total_amount};
    var total_number = {$total_number};
    var user_balance = {$user_info.balance};
    var user_reward = {$user_info.reward};
    var global_result = null;

    $(function(){
        hide_mask();

        $("#submit_order_btn").bind("click", function() { submit_order(); });

        if($("#use_integral") != undefined) {
            $("#use_integral").bind("click", function() { use_mode(); });
        }

        if($("#use_reward") != undefined) {
            $("#use_reward").bind("click", function() { use_mode(); });
        }

        if($("#use_balance") != undefined) {
            $("#use_balance").bind("click", function() { use_mode(); });
        }

        $(".paydetail ul li span").click(function(){
            $(this).siblings().removeClass("on");
            $(this).addClass("on");
            $("#payment").val("wechat");
        })
    });

    function submit_order() {
        var payment = $("#payment").val();
        var consignee = $("#consignee").val();
        var cmobile = $("#phone").val();
        var address = $("#address").val();
        var zipcode = $("#zipcode").val();
        var msg = "";

        if(total_number <= 0) {
            show_message_dialog("请选择要购买的产品");
            return false;
        }

        var data = { "opera":"checkout", "use_integral": false, "use_reward": false, "use_balance": false, "consignee": consignee, "payment": payment, "cmobile": cmobile, "address": address, "zipcode": zipcode };

        if(consignee == "") {
            msg += "-请填写收货人<br/>";
        }

        if(address == "") {
            msg += "-请填写收货地址<br/>";
        }

        if(cmobile == "") {
            msg += "-请填写联系电话<br/>";
        }

        if(payment == "") {
            msg += "-请选择支付方式<br/>";
        }

        if(msg != "") {
            show_message_dialog(msg);
            return false;
        }

        if($("#use_reward") != undefined && $("#use_reward").is(":checked")) {
            data.use_reward = true;
        }

        if($("#use_balance") != undefined && $("#use_balance").is(":checked")) {
            data.use_balance = true;
        }

        var url = "checkout.php";

        show_mask();
        $.post(url, data, submit_order_handler, "json");
    }

    function submit_order_handler(response) {
        hide_mask();
        if(response.error == 0) {
            if(response.status == 1) {
                global_result = response.pay_params;
                show_operation_dialog();
                $("#confirm-message").html(response.msg);
                $("#dialog_confirm_btn").text("查看订单");
                $("#dialog_confirm_cancel").text("立即支付");
                $("#dialog_confirm_btn").click(function(){
                    window.location.href = "order.php";
                });

                $("#dialog_confirm_cancel").click(function(){
                    wx.chooseWXPay({
                        timestamp: global_result.timestamp,
                        nonceStr: global_result.nonce_str,
                        package: 'prepay_id='+global_result.prepay_id,
                        signType: 'MD5',
                        paySign: global_result.sign,
                        success: function (res) {
                            // 支付成功后的回调函数
                            if(res.errMsg == "chooseWXPay:ok") {
                                window.location.href = "order.php";
                            } else {
                                show_message_dialog(res.errMsg+":支付失败");
                                $("#dialog_close_btn,#dialog_close").click(function() {
                                    window.location.href = "order.php";
                                });
                            }
                        }
                    });
                });
            } else {
                show_message_dialog(response.msg);
                $("#dialog_close_btn,#dialog_close").click(function(){
                    window.location.href = "order.php";
                });
            }
        } else {
            show_message_dialog(response.msg);
        }
    }

    function use_mode() {
        var total_amount_tmp = total_amount;

        if($("#use_reward") != undefined && $("#use_reward").is(":checked")) {
            if(total_amount_tmp <= 0) {
                $("#use_reward").attr("checked", false);
                return false;
            }

            if(user_reward > 0) {
                if(user_reward > total_amount_tmp) {
                    total_amount_tmp = 0;
                } else {
                    total_amount_tmp -= user_reward;
                }
            }
        }

        if($("#use_balance") != undefined && $("#use_balance").is(":checked")) {
            if(total_amount_tmp <= 0) {
                $("#use_balance").attr("checked", false);
                return false;
            }

            if(user_balance > 0) {
                if(user_balance > total_amount_tmp) {
                    total_amount_tmp = 0;
                } else {
                    total_amount_tmp -= user_balance;
                }
            }
        }

        $("#order_amount").text("￥"+total_amount_tmp.toFixed(2));
    }

    {if is_weixin()}
    wx.config({
            appId: '{$signPackage.appId}',
            timestamp: {$signPackage.timestamp},
        nonceStr: '{$signPackage.nonceStr}',
        signature: '{$signPackage.signature}',
        jsApiList: [
        'chooseWXPay',
        'closeWindow'
    ]
    });
    {/if}
</script>
{/block}
{block name="footer"}
{/block}