{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>修改银行卡</em></h1>
</header>
{/block}
{block name="content"}
<!-- 添加银行卡 -->
<section class="bank">
    <div class="add-bank">
        <label><span>开户人:</span><input type="text" id="bank_account" name="bank_account" value="{$bank_card.bank_account}" placeholder="请输入开户人姓名"></label>
        <label><span>银行卡号:</span><input type="tel" id="bank_card" name="bank_card" value="{$bank_card.bank_card}" placeholder="请输入银行卡号"></label>
        <label><span>开户银行:</span><input type="text" id="bank" name="bank" value="{$bank_card.bank_name}" placeholder="请输入银行名称"></label>
        <label><span>手机号码:</span><input type="tel" name="mobile" id="mobile" value="{$bank_card.mobile}" placeholder="请输入该卡在银行预留的号码"></label>
        <label><span>账户密码:</span><input type="password" id="password" name="password" value="" placeholder="请输入账户密码"></label>
        <div class="bank-btn">
            <a class="btn" href="javascript:void(0);" onclick="save_bank();return false;">确认修改</a>
            <input type="hidden" name="eid" id="eid" value="{$bank_card.id}"/>
        </div>
    </div>
</section>
<div style="height: 2.2rem;"></div>
<script type="text/javascript">
    function save_bank() {
        var bank_account = $("#bank_account").val();
        var bank_card = $("#bank_card").val();
        var bank = $("#bank").val();
        var password = $("#password").val();
        var mobile = $("#mobile").val();
        var id = $("#eid").val();
        id = parseInt(id);
        var msg = "";

        if(isNaN(id) || id <= 0) {
            msg += "-参数错误<br/>";
        }

        if(bank == "") {
            msg += "-请填写开户银行<br/>";
        }

        if(bank_account == "") {
            msg += "-请填写开户人姓名<br/>";
        }

        if(bank_card == "") {
            msg += "-请填写银行卡号<br/>";
        }

        if(mobile == "") {
            msg += "-请输入该卡在银行预留的号码<br/>";
        }

        if(password == "") {
            msg += "-请输入账户密码<br/>";
        }

        if(msg == "") {
            var url = "bank.php";
            var data = { "opera":"edit", "eid":id, "bank":bank, "bank_account":bank_account, "bank_card":bank_card, "mobile":mobile, "password":password };

            show_mask();
            $.post(url, data, save_bank_handler, "json");
        } else {
            show_message_dialog(msg);
        }
    }

    function save_bank_handler(response) {
        hide_mask();

        show_message_dialog(response.msg);
        if(response.error == 0) {
            $("#dialog_close_btn").attr("href", "javascript:history.back();");
            $("#dialog_close").click(function() {
                history.back();
            });
        }
    }
</script>
{/block}
{block name="footer"}
{/block}