<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="css/mobile.css">
    <link rel="stylesheet" href="css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>编辑收货地址</em></h1>
</header>
<!-- 编辑收货地址 -->
<section class="address">
    <div class="edit-address">
        <label for="name"><span>收货人:</span><input type="text" id="name" name="name" placeholder="" value="隔壁老王"></label>
        <label for="province"><span>选择地区:</span>
            <select id="province" name="province">
                <option value="0">省份</option>
                <option value="1" selected>广东省</option>
            </select>
        </label>
        <label for="city"><span>&nbsp;</span>
            <select id="city" name="city">
                <option value="0">城市</option>
                <option value="0" selected>广州市</option>
            </select>
        </label>
        <label class="distinct" for="distinct"><span>&nbsp;</span>
            <select id="distinct" name="distinct">
                <option value="0">地区</option>
                <option value="1" selected>黄浦区</option>
            </select>
        </label>
        <label><span>街道地址:</span><input type="text" id="address" name="address" value="萝岗科学大道"></label>
        <label><span>手机号码:</span><input type="text" id="cellphone" name="cellphone" value="13666666666"></label>
        <label><span>设为默认地址</span><input type="checkbox" id="set_default" class="c_checkbox" checked></label>
        <div class="address-btn">
            <a class="btn" href="#" onclick="return false;"><i class="icon">&#xe612;</i> 新增</a>
            <a class="btn" href="#" onclick="return false;">保存</a>
        </div>
    </div>
</section>
<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>

</body>
</html>
