{extends file="index.phtml"}
{block name="header"}
{/block}
{block name="content"}
<!-- 用户基本信息 -->
<section class="home">
    <header class="user-info">
        <section class="user-basic">
            <img class="user-avatar" src="{if $member_info.wx_headimg eq ''}{$template_dir}images/wang.jpg{else}{$member_info.wx_headimg}{/if}" alt="用户">
            <div class="user-name">
                {$member_info['name']}&nbsp;&nbsp;
                {$lang.level[{$member_info.level_id}]}
            </div>
            <section class="remaining">
                <a href="balance.php"><em>余额&nbsp;{price_format($member_info['balance'])}</em></a>
                <a href="reward.php"><em>奖金&nbsp;{price_format($member_info['reward'])}</em></a>
                <a href="integral.php"><em>积分&nbsp;{price_format($member_info['integral'])}</em></a>
            </section>
        </section>
        <section class="user-stat" style="display: none">
            <a id="shop_collect_number" href="reward_await.php"><em></em>待发奖金</a>
            <a id="product_collect_number" href="reward_await.php?type=1"><em></em>待发推荐奖</a>
            <a id="read_history_count" href="reward_await.php?type=2"><em></em>待发管理奖</a>
        </section>
    </header>
    <!-- 我的资产 -->
    <section class="f-section wealth-section">
        <a class="slide-link" href="wallet.php">
            <span class="icon" style="background-color: #7dc4fb;">&#xe61c;</span>
            我的资产            <em>查看我的全部资产</em>
        </a>
        <nav class="order-nav">
            <ul>
                <li style="width: 33.333333333333%">
                    <a href="balance.php" >
                        <p class="icon">&#xe614;</p>
                        余额
                    </a>
                </li>
                <li style="width: 33.333333333333%">
                    <a href="reward.php">
                        <p class="icon">&#xe626;</p>
                        奖金
                    </a>
                </li>
                <li style="width: 33.333333333333%">
                    <a href="integral.php">
                        <p class="icon">&#xe616;</p>
                        积分
                    </a>
                </li>
            </ul>
        </nav>
    </section>
    <!-- 个人中心功能菜单 -->
    <section class="f-section">
        <a class="slide-link" href="order.php">
            <span class="icon" style="background-color: #009a44;">&#xe622;</span>我的订单
        </a>
        {if $member_info.level_id gt 1}
        <a class="slide-link" href="recommend.php">
            <span class="icon" style="background-color: #ff0000;">&#xe628;</span>报单
        </a>
        <a class="slide-link" href="qrcode.php?ticket={base64_encode($member_info.wx_openid)}">
            <span class="icon" style="background-color: #c2cb5a;">&#xe604;</span>推广名片
        </a>
        {if $member_info.view_network}
        <a class="slide-link" href="team.php">
            <span class="icon" style="background-color: #f29902;">&#xe620;</span>我的团队
        </a>
        {/if}
        {/if}
        <a class="slide-link" href="reward.php">
            <span class="icon" style="background-color: #80c269;">&#xe624;</span>我的奖金
        </a>
        <a class="slide-link" href="recharge.php">
            <span class="icon" style="background-color: #008fbf;">&#xe61c;</span>我要充值
        </a>
        {if $member_info.status neq 4}
        <a class="slide-link" href="withdraw.php">
            <span class="icon" style="background-color: #fb9065;">&#xe621;</span>我要提现
        </a>
        {/if}
        <a class="slide-link" href="bank.php">
            <span class="icon" style="background-color: #f29ec2;">&#xe623;</span>我的银行卡
        </a>
        <a class="slide-link" href="profile.php">
            <span class="icon" style="background-color: #d0c0a6;">&#xe600;</span>个人信息
        </a>
    </section>
    <section class="f-section" style="display: none">
        <a class="slide-link" href="javascript:alert('建设中...');">
            <span class="icon" style="background-color: #acd697;">&#xe61e;</span>意见反馈
        </a>
    </section>
</section>
<div style="height: 2.2rem;"></div>
{/block}

{block name="footer"}
<section class="menu">
    <ul>
        <li><a href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="article_list.php"><em class="icon">&#xe603;</em><span>资讯</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="user.php"><em class="icon">&#xe600;</em><span>我</span></a></li>
    </ul>
</section>
{/block}