<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name}">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/index.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
    <script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
    {if is_weixin()}
    <script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.1.0.js"></script>
    {/if}
</head>
<body>
{block name="header"}
    <!-- 首页头部 -->
    <header class="header">
        <div class="logo">
            <a href="#">{$config.site_name}</a>
        </div>
        <div class="search_box" style="text-align: center">
            {$config.site_name}
            <!--
            <a href="#" >
                <div class="search">
                    <form method="get" action="">
                        <div class="text_box">
                            <input id="keyword" name="keyword" type="text" placeholder="搜索商品/店铺" class="keyword text" onkeydown="this.style.color='#404040'" autocomplete="off">
                        </div>
                        <input type="submit" value="" class="submit" dd_name="搜索">
                    </form>
                </div>
            </a>
            -->
        </div>
    </header>
{/block}
{block name="content"}
    <!-- 广告轮播区 -->
    <section id="focus" class="focus">
        <div class="hd">
            <ul></ul>
        </div>
        <div class="bd">
            <ul>
                {foreach from=$cycle_ad item=ad}
                <li><a href="#"><img _src="{$ad.img|build_url}" src="{$template_dir}images/blank.png" /></a></li>
                {/foreach}
            </ul>
        </div>
    </section>
    <script type="text/javascript" src="{$template_dir}js/TouchSlide.1.1.js"></script>
    <script type="text/javascript">
    TouchSlide({
        slideCell:"#focus",
        titCell:".hd ul", //开启自动分页 autoPage:true ，此时设置 titCell 为导航元素包裹层
        mainCell:".bd ul",
        effect:"left",
        autoPlay:true,//自动播放
        autoPage:true, //自动分页
        switchLoad:"_src" //切换加载，真实图片路径为"_src"
    });
    </script>
    <!-- 广告轮播区 end -->

    <!-- 首页公告区 -->
    <section class="index-news clearfix">
        <div class="index-news-l fl">
            <span class="icon">&#xe613;</span>
        </div>
        <div id="myscroll" class="index-news-r">
            <ul id="notice" class="news-title">
                {foreach from=$notice item=content}
                <li><a href="article.php?id={$content.id}">{$content.title|escape}</a></li>
                {/foreach}
            </ul>
        </div>
    </section>
    <script type="text/javascript" src="{$template_dir}js/scrolltext.js"></script>
    <script type="text/javascript">
        var newsHeight = $(".index-news").height();
        if(document.getElementById("notice")){
            var scrollup = new ScrollText("notice");
            scrollup.LineHeight =  (newsHeight ==120)?40:20;//单排文字滚动的高度
            scrollup.Amount = 1;            //注意:子模块(LineHeight)一定要能整除Amount.
            scrollup.Delay = 35;           //延时
            scrollup.Start();             //文字自动滚动
            scrollup.Direction = "down"; //文字向下滚动
        }
    </script>

    <!-- 首页功能区 -->
    <ul class="index-nav">
        <li><a href="reward.php" title="我的奖金"><img class="" src="{$template_dir}images/jifen.png"><span>我的奖金</span></a></li>
        <li><a href="withdraw.php" title="账户提现"><img class="" src="{$template_dir}images/tixian.png"><span>账户提现</span></a></li>
        <li><a href="order.php" title="我的订单"><img class="" src="{$template_dir}images/dingdan.png"><span>我的订单</span></a></li>
        {if $member_info.level_id eq 1}
        <li><a href="levelup.php" title="成为会员"><img class="" src="{$template_dir}images/dizhi.png"><span>成为会员</span></a></li>
        {else}
        <li><a href="recommend.php" title="报单"><img class="" src="{$template_dir}images/dizhi.png"><span>报单</span></a></li>
        {/if}
    </ul>

    <!-- 推荐产品 -->
    <section class="floor">
    <h2>
        <a class="title"><i class="icon">&#xe610;</i>热荐产品 </a>
    </h2>
    </section>
    <section class="product-list">
        <ul>
            {foreach from=$product_list item=product}
            <li>
                <a href="product.php?id={$product.id}">
                    <img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$product.img}" alt="{$product.name|escape}">
                    <dl class="arrow">
                        <dt>{$product.name|escape}</dt>
                        <dd>￥{$product.price|string_format:'%.2f'}</dd>
                    </dl>
                </a>
            </li>
            {/foreach}
        </ul>
    </section>

    <!-- 商家推荐区 -->
    <!--
    <section class="floor">
    <h2>
        <a class="title"><i class="icon">&#xe610;</i>商家推荐</a>
    </h2>
    </section>
    {foreach from=$perform_ad_4 item=ad}
    <section class="index-floor">
        <div class="floor-con">
            <a href="{$ad.url}"><img src="{$ad.img|build_url}" alt="{$ad.alt}" width="100%"></a>
        </div>
    </section>
    {/foreach}
    -->

    <div style="height:2.2rem; "></div>

    <script type="text/javascript" src="{$template_dir}js/jquery.lazyload.min.js"></script>
    <script type="text/javascript">
        $(function() {
            $("img.lazy").lazyload({
                effect : "fadeIn"
            });
        });
    </script>
{/block}
{block name="footer"}
<section class="menu">
    <ul>
        <li><a class="active" href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="article_list.php"><em class="icon">&#xe603;</em><span>资讯</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a href="user.php"><em class="icon">&#xe600;</em><span>我</span></a></li>
    </ul>
</section>
{/block}
{block name="dialog"}
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="confirm_dialog" style="display: none;">
        <p id="confirm-message"></p>
        <ul class="cd-buttons">
            <li><a id="dialog_confirm_btn" href="javascript:void(0);"></a></li>
            <li><a id="dialog_confirm_cancel" href="javascript:close_operation_dialog('confirm_dialog');"></a></li>
        </ul>
        <a href="javascript:close_operation_dialog('confirm_dialog');" class="cd-popup-close img-replace" id="dialog_confirm_close">X</a>
    </div>

    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();" id="dialog_close_btn">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace" id="dialog_close">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript">
    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").html(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }

    function show_operation_dialog() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#confirm_dialog").show();
    }

    function close_operation_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#confirm_dialog").hide();
    }
</script>
{/block}
</body>
</html>
