{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>成为会员</em></h1>
</header>
{/block}
{block name="content"}
<!-- 确定订单 -->
<section class="checkout-con">
    <section class="userinfo" style="background: #fff;">
        <div class="edit-userinfo">
            <label><span>真实姓名:</span>
                <input name="name" id="name" type="text" value="" placeholder="请输入真实姓名"/>
            </label>
            <label><span>手机号码:</span>
                <input name="mobile" id="mobile" type="tel" value="{$member_info.mobile}" placeholder="请输入手机号码" onblur="verify_mobile();"/>
            </label>
        </div>
    </section>

    <section class="product-selection preferential">
        {foreach from=$product_list item=product name=product_list}
        <div class="product-optional">
            <input type="radio" name="product_sn" class="c_checkbox" data-price="{$product.price|floatval}" value="{$product.product_sn}" {if $smarty.foreach.product_list.first}checked="checked"{/if}>
            <img src="{$product.img}"/>
            <div class="product-info">
                <p class="product-name">{$product.name|escape}</p>
                <p class="product-price">￥{$product.price|string_format:'%.2f'}</p>
                <p class="product-meta">报单等级：{$lang.level[$product.target_level]}</p>
            </div>
        </div>
        {/foreach}
    </section>

    <div class="edit-address preferential border_bottom">
        <div class="w_panel border_lr order_main border_top">
            <h4 class="h_title">
                收货信息
            </h4>
        </div>
        <div class="single_line_div leavemessage">
            <span><input name="consignee" id="consignee" placeholder="收货人" value="" data-original-length="0" type="text"></span>
        </div>
        <div class="single_line_div leavemessage">
            <span><input name="zipcode" id="zipcode" placeholder="邮政编码" value="" data-original-length="0" type="text"></span>
        </div>
        <div class="single_line_div leavemessage">
            <span><input name="address" id="address" placeholder="收货地址" value="" data-original-length="0" type="text"></span>
        </div>
        <div class="single_line_div leavemessage">
            <span><input name="cmobile" id="cmobile" placeholder="联系电话" value="" data-original-length="0" type="text"></span>
        </div>
    </div>

    {if ($member_info.integral gt 0 or $member_info.reward gt 0 or $member_info.balance gt 0)}
    <section class="preferential border_bottom">
        <ul class="preferential-list">
            {if $member_info.reward gt 0 and $member_info.level_id gt 0}
            <li>
                可用奖金: {$member_info.reward}元
                <input name="use_reward" id="use_reward" type="checkbox" class="fr c_checkbox" value="use_reward"/>
            </li>
            {/if}
            {if $member_info.balance gt 0}
            <li>
                可用余额: {$member_info.balance}元
                <input name="use_balance" id="use_balance" type="checkbox" class="fr c_checkbox" value="use_balance"/>
            </li>
            {/if}
        </ul>
    </section>
    {/if}

    <!-- 支付详情 -->
    <div style="height: 60px;"></div>
    <input type="hidden" name="payment_id" id="payment_id" value="1"/>
    <!-- 提交订单 -->
    <section class="order-submit">
        <div class="order_review">
            <div style="float:left;width:69%;padding:5px 0;line-height:41px;">
                <div style="float:left;">
                    <span style="font-size:12px;display:inline-block;color:#464646;">应付总额: </span>
                    <a class="red_money" style="margin:0 0 0 5px;font-size:14px;display:inline-block;" id="order_amount">￥0.00 </a>
                    <br>
                </div>
            </div>
            <a href="javascript:void(0);" id="submit_order_btn" class="yellow_btn">成为会员</a>
        </div>
    </section>
</section>

<script type="text/javascript">
    var total_amount = 0;
    var user_balance = {$member_info.balance|floatval};
    var user_reward = {$member_info.reward|floatval};
    var mobile = '{$member_info.mobile}';
    var pay_params = null;

    $(function(){
        hide_mask();

        $("#submit_order_btn").bind("click", function() { submit_order(); });

        if($("#use_integral") != undefined) {
            $("#use_integral").bind("click", function() { caculate_fee(); });
        }

        if($("#use_reward") != undefined) {
            $("#use_reward").bind("click", function() { caculate_fee(); });
        }

        if($("#use_balance") != undefined) {
            $("#use_balance").bind("click", function() { caculate_fee(); });
        }

        $('input[name=product_sn]').click(function() {
            caculate_fee();
        });

        caculate_fee();

        {if $member_info.status eq 1}
        show_message_dialog('您的会员身份尚未激活.<br/>请先支付注册订单激活身份');
        $("#dialog_close_btn").click(function(){
            window.location.href = "order.php";
        });
        $("#dialog_close").click(function(){
            window.location.href = "index.php";
        });
        {/if}
    });

    function verify_mobile() {
        var mobile = $("#mobile").val();

        if(mobile == "") {
            show_message_dialog("请输入手机号码");
            return false;
        }

        var url = "data_center.php";
        var data = { "opera":"verify_mobile", "mobile":mobile, "mode":"unique" };

        show_mask();
        $.post(url, data, verify_mobile_handler, "json");
    }

    function verify_mobile_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#mobile-show").text(response.mobile_mask);
            mobile = response.mobile;
        } else {
            show_message_dialog(response.msg);
            mobile = "";
        }
    }

    function caculate_fee() {
        $('input[name=product_sn]').each(function() {
            if($(this).prop('checked')) {
                total_amount = parseFloat($(this).attr('data-price'));

                if(isNaN(total_amount) || total_amount <= 0) {
                    total_amount = 0;
                }
            }
        });

        if($("#use_reward").length && $("#use_reward").is(":checked")) {

            if(total_amount > 0) {
                if(total_amount > user_reward) {
                    total_amount -= user_reward;
                } else {
                    total_amount = 0;
                }
            }
        }

        if($("#use_balance").length && $("#use_balance").is(":checked")) {

            if(total_amount > 0) {
                if(total_amount > user_balance) {
                    total_amount -= user_balance;
                } else {
                    total_amount = 0;
                }
            }
        }

        $("#order_amount").text("￥"+total_amount.toFixed(2));
    }

    function submit_order() {
        var msg = "";
        var product_sn = '';
        var name = $("#name").val();

        if(name == "") {
            msg += "-请填写真实姓名<br/>";
        }

        if(mobile == "") {
            msg += "-请填写手机号码<br/>";
        }

        $('input[name=product_sn]').each(function() {
            if($(this).prop('checked')) {
                product_sn = $(this).val();
            }
        });

        var data = {
            opera: "submit_order",
            use_integral: false,
            use_reward: false,
            use_balance: false,
            product_sn: product_sn,
            name: name,
            mobile: mobile,
            consignee: $('#consignee').val(),
            cmobile: $('#cmobile').val(),
            address: $('#address').val(),
            zipcode: $('#zipcode').val()
        };

        if(data.product_sn == '') {
            msg += '-请选择报单产品<br/>';
        }

        if(data.consignee == '') {
            msg += '-请填写收货人姓名<br/>';
        }

        if(data.address == '') {
            msg += '-请填写收货地址<br/>';
        }

        if(data.cmobile == '') {
            msg += '-请填写联系电话<br/>';
        }

        if($("#use_integral").length && $("#use_integral").is(":checked")) {
            data.use_integral = true;
            if(total_amount < 0) {
                $("#use_integral").attr("checked", false);
                return false;
            }
        }

        if($("#use_reward").length && $("#use_reward").is(":checked")) {
            data.use_reward = true;
            if(total_amount < 0) {
                $("#use_reward").attr("checked", false);
                return false;
            }
        }

        if($("#use_balance").length && $("#use_balance").is(":checked")) {
            data.use_balance = true;
            if(total_amount < 0) {
                $("#use_balance").attr("checked", false);
                return false;
            }
        }

        if(msg != "") {
            show_message_dialog(msg);
            return false;
        }

        var url = "levelup.php";

        show_mask();
        $.post(url, data, submit_order_handler, "json");
    }

    function submit_order_handler(response) {
        hide_mask();
        if(response.error == 0) {
            if(response.status == 3) {
                show_message_dialog(response.msg);
                $("#dialog_close_btn,#dialog_close").click(function(){
                    window.location.reload();
                });
            } else if(response.status == 1) {
                //根据订单状态判断是否发起微信支付
                $("#confirm-message").html(response.msg);
                $("#dialog_confirm_cancel").text("现在支付");
                $("#dialog_confirm_btn").text("查看订单");
                pay_params = response.pay_params;
                $("#dialog_confirm_cancel").click(function(){
                    window.location.href = 'topay.php';
                });
                $("#dialog_confirm_btn,#dialog_confirm_close").click(function(){
                    window.location.href = "order.php";
                });
                show_operation_dialog();
            }
        } else {
            show_message_dialog(response.msg);
        }
    }
</script>
{/block}
{block name="footer"}
<script type="text/javascript">
</script>
{/block}