<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>登陆</em></h1>
</header>
<!-- 登陆页面 -->
<section class="login register">
    <section class="login-con register-con">
        <div class="inp user bg">
            <span class="icon"></span>
            <span class="input">
                <input id="account" name="account" type="text" placeholder="请输入你的手机号/会员卡号">
            </span>
            <span class="more"></span>
            <span class="clear" style="display: none;"></span>
        </div>
        <div class="inp pw bg">
            <span class="icon"></span>
            <span class="input">
                <input id="password" type="password" name="password" placeholder="密码"/>
            </span>
            <span class="clear" style="display: none;"></span>
        </div>
        <div class="pw_contain">
            <div class="inp graphics short small bg">
                <span class="input">
                    <input class="identify_code" type="text" placeholder="请输入图形验证码" id="pic_code"/>
                </span>
                <span class="clear" style="display: none;"></span>
            </div>
            <div class="identify">
                <a class="refresh" href="javascript:;" onclick="refresh_code();">refresh</a>
                <img class="repic" src="code.php" alt="验证码">
            </div>
        </div>
        <a class="btn" href="javascript:void(0);" id="login_btn">登录</a>
        <dl class="func">
            <dt><a href="forgot.php">找回密码</a></dt>
            <dd><a href="register.php">注册</a></dd>
        </dl>
    </section>
</section>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();" id="dialog_close_btn">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace" id="dialog_close">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    $(function(){
        $("#login_btn").click(function(){
            verify_memeber_info();
        });
    });

    function verify_memeber_info() {
        var code = $("#pic_code").val();
        var account = $("#account").val();
        var password = $("#password").val();
        var msg = "";

        if(account == "") {
            msg += "-请输入手机号码/会员卡号<br/>";
        }

        if(password == "") {
            msg += "-请输入密码<br/>";
        }

        if(code == "") {
            msg += "-请输入图形验证码<br/>";
        }

        if(msg != "") {
            show_message_dialog(msg);
            return false;
        }

        var url = "data_center.php";
        var data = { "opera":"login", "code":code, "account":account, "password":password, "ref": document.referrer };

        show_mask();
        $.post(url, data, verify_member_info_handler, "json");
    }

    function verify_member_info_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#dialog_close").click(function(){
                window.location.href = response.referer;
            });

            $("#dialog_close_btn").click(function(){
                window.location.href = response.referer;
            });
        }
        show_message_dialog(response.msg);
    }

    function refresh_code() {
        $(".repic").attr("src", "code.php");
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").html(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }
</script>
</body>
</html>
