{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>绑定</em></h1>
</header>
{/block}
{block name="content"}
<!-- 登陆页面 -->
<section class="login register">
    <section class="login-con register-con">
        <div class="inp user bg">
            <span class="icon"></span>
            <span class="input">
                <input id="account" name="account" type="text" placeholder="请输入你的手机号/会员卡号">
            </span>
            <span class="more"></span>
            <span class="clear" style="display: none;"></span>
        </div>
        <div class="inp pw bg">
            <span class="icon"></span>
            <span class="input">
                <input id="password" type="password" name="password" placeholder="密码"/>
            </span>
            <span class="clear" style="display: none;"></span>
        </div>
        <div class="pw_contain">
            <div class="inp graphics short small bg">
                <span class="input">
                    <input class="identify_code" type="text" placeholder="请输入图形验证码" id="pic_code"/>
                </span>
                <span class="clear" style="display: none;"></span>
            </div>
            <div class="identify">
                <a class="refresh" href="javascript:;" onclick="refresh_code();">refresh</a>
                <img class="repic" src="code.php" alt="验证码">
            </div>
        </div>
        <a class="btn" href="javascript:void(0);" id="login_btn">绑定</a>
        <dl class="func" style="display: none">
            <dt><a href="forgot.php">找回密码</a></dt>
            <dd><a href="register.php">注册</a></dd>
        </dl>
    </section>
</section>

<script type="text/javascript">
    $(function(){
        $("#login_btn").click(function(){
            verify_memeber_info();
        });
    });

    function verify_memeber_info() {
        var code = $("#pic_code").val();
        var account = $("#account").val();
        var password = $("#password").val();
        var msg = "";

        if(account == "") {
            msg += "-请输入手机号码/会员卡号<br/>";
        }

        if(password == "") {
            msg += "-请输入密码<br/>";
        }

        if(code == "") {
            msg += "-请输入图形验证码<br/>";
        }

        if(msg != "") {
            show_message_dialog(msg);
            return false;
        }

        var url = "data_center.php";
        var data = { "opera":"login", "code":code, "account":account, "password":password, "ref": document.referrer };

        show_mask();
        $.post(url, data, verify_member_info_handler, "json");
    }

    function verify_member_info_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#dialog_close").click(function(){
                window.location.href = response.referer;
            });

            $("#dialog_close_btn").click(function(){
                window.location.href = response.referer;
            });
        }
        show_message_dialog(response.msg);
    }

    function refresh_code() {
        $(".repic").attr("src", "code.php");
    }
</script>
{/block}

{block name="footer"}{/block}