{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>系统公告</em></h1>
</header>
{/block}
{block name="content"}
<section class="home">
    <section class="f-section">
        {foreach from=$article_list item=article}
        <a class="slide-link" href="article.php?id={$article.id}">
            <i class="link-tag"></i>{$article.title}
        </a>
        {/foreach}
    </section>
</section>
<div style="height: 2.2rem;"></div>
{/block}