{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>系统公告</em></h1>
</header>
{/block}
{block name="content"}
<section class="home">
    <section class="f-section">
        {foreach from=$article_list item=article}
        <a class="slide-link" href="article.php?id={$article.id}">
            <i class="link-tag"></i>{$article.title}
        </a>
        {/foreach}
    </section>
</section>
<div style="height: 2.2rem;"></div>
{/block}

{block name="footer"}
<section class="menu">
    <ul>
        <li><a href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a class="active" href="article_list.php"><em class="icon">&#xe603;</em><span>资讯</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a href="user.php"><em class="icon">&#xe600;</em><span>我</span></a></li>
    </ul>
</section>
{/block}