<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
{foreach from=$article_list item=article}
<div class="article-list-item">
    <a href="article.php?id={$article.id}">
        <img src="{if $article.original}./{$article.original}{else}{$template_dir}image/bg_pic.png{/if}"/>
        <p class="clearfix">{$article.title|truncate:8:'...'}</p>
    </a>
</div>
{/foreach}
<!--
<li>
    <a href="article.php?id={$article.id}">
        <dl class="arrow">
            <dt>{$article.title}<span>{date("Y/m/d", $article.add_time)}</span></dt>
            <dd>{$article.description}</dd>
        </dl>
    </a>
</li>
-->
