<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header" style="position:fixed">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>{$title}</em></h1>
</header>

<!-- 内容开始 -->
<section class="newslist">
    {if $section_list}
    <nav class="newslist-nav">
        <ul>
            {if $all eq 'all'}
            <li id="index_all" class="on" style="width: {$width}%"><a href="javascript:sort('{$all}');">全部</a></li>
            {/if}
            {foreach from=$section_list item=section}
            <li id="index_{$section.id}" style="width: {$width}%"><a href="javascript:sort('{$section.id}');">{$section.section_name}</a></li>
            {/foreach}
        </ul>
    </nav>
    {/if}
    <ul class="newslist-con" id="news-list">
        {include file="news-list-item.phtml"}
        <!--
        {foreach from=$article_list item=article}
        <li>
            <a href="article.php?id={$article.id}">
                <dl class="arrow">
                    <dt>{$article.title}<span>{date("Y/m/d", $article.add_time)}</span></dt>
                    <dd>{$article.description}</dd>
                </dl>
            </a>
        </li>
        {/foreach}
        -->
    </ul>
</section>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();" id="dialog_close_btn">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace" id="dialog_close">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    function sort(mode) {
        $("#index_"+mode).siblings().removeClass("on");
        $("#index_"+mode).addClass("on");

        show_mask();
        $.post("article_list.php", { "opera":"sort", "mode":mode }, sort_handler, "json");
    }

    function sort_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#news-list").html(response.content);
        } else {
            show_message_dialog(response.msg);
        }
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").text(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }
</script>
</body>
</html>
