<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我的订单</em></h1>
</header>
<!-- 筛选导航栏-->
<nav class="ol_select_bar">
    <ul>
        <a id="index_0" href="javascript:sort_order('0');" class="hover"><li>全部</li></a>
        <a id="index_1" href="javascript:sort_order('1');"><li>待付款</li></a>
        <a id="index_6" href="javascript:sort_order('6');"><li>待收货</li></a>
        <a id="index_7" href="javascript:sort_order('7');"><li>待评价</li></a>
        <a id="index_8" href="javascript:sort_order('8');"><li>售后</li></a>
    </ul>
</nav>

<!-- 订单列表 -->
<section class="order-list" id="order-list">
    {if $order_list}
    {foreach from=$order_list item=order}
    <div class="block">
        <div class="order_list">
            <!--非当当自营显示店铺入口-->
            <div class="shop_title">
                <a href="shop.php?sn={$order.business_account}">
                    <!--店铺名称-->
                    <div class="fl">
                        {$order.shop_name}
                    </div>
                    <span class="fr right_arrow"></span>
                </a>

            </div>
            <!--分包商品信息-->
            <div class="cart_item prd_ebook">
                <a href="order.php?act=detail&sn={$order.order_sn}">
                    <!--电子书加签-->
                    {foreach from=$order.order_detail item=od}
                    <!--包裹图片-->
                    <img src="{$template_dir}images/product_1.jpg" class="fl pro_pic">
                    {/foreach}
                    <!--包裹详情-->
                    <div class="detail">
                        <!--包裹状态-->
                        <div class="fr prd_state">
                            <!--状态文字-->
                            <div class="prd_state_title">
                                {$order.show_status}
                            </div>
                        </div>
                        <!--包裹名称显示，多件产品，显示包裹编号，一件产品显示产品名称-->
                        <p class="fl prd_tit">
                            {if count($order.order_detail) eq 1}
                            {$order.order_detail.0.product_name}
                            {else}
                            {/if}
                        </p>
                    </div>
                </a>
            <!--数量价格信息-->
            <div class="detail2">
                共<span>{count($order.order_detail)}</span>件商品
                <span>　总价：</span><span class="order_price">￥{$order.amount}</span>
            </div>
            <!--操作按键-->
            <div class="detail3">
                {if $order.status eq 7}
                <a href="javascript:comment('{$order.order_sn}');" class="orange_hollow">晒单评论</a>
                <a href="javascript:rollback('{$order.order_sn}');">申请退单</a>
                {/if}
                {if $order.status eq 6}
                <a href="order.php?act=express_info&order_sn={$order.order_sn}" onclick="show_mask()">查看物流</a>
                <a href="javascript:receive('{$order.order_sn}');" class="orange_hollow">确认收货</a>
                {/if}
                {if $order.status eq 4}
                <a href="javascript:rollback('{$order.order_sn}');">申请退单</a>
                {/if}
                {if $order.status eq 1}
                <a href="javascript:pay_now('{$order.order_sn}');" class="orange_hollow">立即支付</a>
                <a href="javascript:cancel_order('{$order.order_sn}');">取消订单</a>
                {/if}
            </div>
        </div>
        </div>
    </div>
    {/foreach}
    {else}
    <div class="block">
        <div class="empty-con">
            <span class="icon">&#xe63d;</span>
            <span class="empty-tips">您还未订购过任何商品!</span>
            <span class="empty-btn">
                <a href="index.php" class="btn">去逛逛</a>
            </span>
        </div>
    </div>
    {/if}
</section>
<div style="height: 2.8rem;"></div>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();" id="dialog_close_btn">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace" id="dialog_close">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.php"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="#"><em class="icon">&#xe604;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    $(function(){
        var status = {$status};
        $("#index_"+status).siblings().removeClass("hover")
        $("#index_"+status).addClass("hover");
    });

    function sort_order(mode) {
        var url = "order.php";
        var data = { "opera":"sort", "mode":mode };

        show_mask();
        $("#index_"+mode).siblings().removeClass("hover")
        $("#index_"+mode).addClass("hover");
        $.post(url, data, sort_order_handler, "json");
    }

    function sort_order_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#order-list").html(response.content);
        } else {
            show_message_dialog(response.msg);
        }
    }

    function comment(order_sn) {
        if(order_sn != '') {
            window.location.href = "order.php?act=comment&sn="+order_sn;
        }
    }

    function pay_now(order_sn) {
        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"pay_now", "order_sn":order_sn };

            show_mask();
            $.post(url, data, pay_now_handler, "json");
        }
    }

    function pay_now_handler(response) {
        if(response.error == 0) {
            window.location.href = "topay.php";
        } else {
            hide_mask();
            show_message_dialog(response.msg);
        }
    }

    function cancel_order(order_sn) {
        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"cancel", "order_sn":order_sn };

            show_mask();
            $.post(url, data, cancel_order_handler, "json");
        }
    }

    function cancel_order_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#dialog_close_btn, #dialog_close").click(function () {
                window.location.reload();
            });
        }

        show_message_dialog(response.msg);
    }

    function receive(order_sn) {
        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"receive", "order_sn":order_sn };

            show_mask();
            $.post(url, data, receive_handler, "json");
        }
    }

    function receive_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#dialog_close_btn, #dialog_close").click(function () {
                window.location.reload();
            });
        }

        show_message_dialog(response.msg);
    }

    function rollback(order_sn) {
        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"rollback", "order_sn":order_sn };

            show_mask();
            $.post(url, data, receive_handler, "json");
        }
    }

    function rollback_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#dialog_close_btn, #dialog_close").click(function () {
                window.location.reload();
            });
        }

        show_message_dialog(response.msg);
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").html(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }
</script>
</body>
</html>
