{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>订单详情</em></h1>
</header>
{/block}
{block name="content"}
<!-- 确定订单 -->
<section class="orderdetail-con">
    <!-- 订单状态 -->
    <section class="order-status border_bottom">
        <div class="status-title red-font"><i class="icon">&#xe60e;</i> &nbsp;订单状态：{$order.show_status}</div>
        {if $order.status eq 1}
        <a href="#">
            <div class="status-con">
                <div class="status-content">
                    <span>您的订单已经成功提交，为避免心头宝被抢走，赶紧去付款吧！</span>
                </div>
            </div>
        </a>
        {/if}
    </section>
    <!-- 收货地址 -->
    <div class="colorBar shadow_top" style="margin-top:6px;"></div>
    <section class="address">
        <div class="address-title"><i class="icon">&#xe60c;</i> &nbsp;收货信息</div>
        <div class="address-con">
            <div class="address-user">
                <span>{$order.consignee}</span>
                <span>{$order.phone}</span>
            </div>
            <div class="address-detail">
                <div class="address-content">
                    {$order.address}
                </div>
            </div>
        </div>
    </section>
    <div class="colorBar shadow_top"></div>
    <!-- 订单产品详情 -->
    <section class="orders">
        <div class="border_lr trans_div order_action_block border_bottom">
            <div>
                <div>
                    <ul class="product_ul">
                        {foreach from=$order.order_detail item=od}
                        <li>
                            <div class="box">
                                <div class="product_cover">
                                    <img width="100%" src="{$od.img|build_url}">
                                </div>
                                <div class="product_info cr_2">
                                    <p class="product_name">{$od.name}</p>
                                    <p>
                                        <span class="red_money">￥{$od.price}</span>
                                        <span>&nbsp;×{$od.number}</span>
                                    </p>
                                    <!--<a class="red_btn">付款</a>-->
                                </div>
                            </div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
                <hr color="#E5E5E5" class="line_l" size="1">
                <div class="single_line_div2 border_0" id="shipAndPay">
                    <span class="t_span">产品总额：</span>
                    <span class="right_action"><em class="red_money">￥{$order.product_amount}</em></span>
                    <br/>
                    {*
                    <span class="t_span">运费：</span>
                    <span class="right_action"><em class="red_money">￥{$order.delivery_fee}</em></span>
                    <br/>
                    *}
                    {if $order.integral_paid gt 0}
                    <span class="t_span">积分抵用：</span>
                    <span class="right_action"><em style="color: #787878;">- ￥{$order.integral_paid}</em></span>
                    <br/>
                    {/if}
                    {if $order.reward_paid gt 0}
                    <span class="t_span">奖金抵用：</span>
                    <span class="right_action"><em style="color: #787878;">- ￥{$order.reward_paid}</em></span>
                    <br/>
                    {/if}
                    {if $order.balance_paid gt 0}
                    <span class="t_span">预付款抵用：</span>
                    <span class="right_action"><em style="color: #787878;">- ￥{$order.balance_paid}</em></span>
                    <br/>
                    {/if}
                    <span class="t_span">实付总额（含运费）：</span>
                    <span class="right_action"><em class="red_money">￥{$order.total_amount}</em></span>
                </div>
            </div>
        </div>
    </section>
    <!-- 订单状态 -->
    <section class="order-status-detail border_bottom">
        <div class="order-status-show">
            <p>订单编号：{$order.order_sn}</p>
            <p>创建时间：{date("Y-m-d H:i:s", $order.add_time)}</p>
            <p>付款时间：{if $order.pay_time eq ""}暂无记录{else}{date("Y-m-d H:i:s", $order.pay_time)}{/if}</p>
        </div>
    </section>
    <div style="height: 60px;"></div>
    <!-- 提交订单 -->
    {if $order.status lt 2}
    <section class="order-submit">
        <div class="order_review">
            <div style="float:left;width:69%;padding:5px 0;line-height:41px;">
                <div style="float:left;">
                    <span style="font-size:12px;display:inline-block;color:#464646;">共{count($order.order_detail)}件商品，总额(含运费)</span>
                    <a class="red_money" style="margin:0 0 0 5px;font-size:14px;display:inline-block;">￥{$order.total_amount} </a>
                    <br>
                </div>
            </div>
            <a href="javascript:pay_now('{$order.order_sn}');" class="yellow_btn">前去付款</a>
        </div>
    </section>
    {/if}
</section>
<script type="text/javascript">
    function pay_now(order_sn) {
        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"pay_now", "order_sn":order_sn };

            show_mask();
            $.post(url, data, pay_now_handler, "json");
        }
    }

    function pay_now_handler(response) {
        if(response.error == 0) {
            window.location.href = 'topay.php';
        } else {
            hide_mask();
            show_message_dialog(response.msg);
        }
    }
</script>
{/block}
{block name="footer"}
{/block}