{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我的订单</em></h1>
</header>
{/block}
{block name="content"}
<!-- 订单列表 -->
<section class="order-list" id="order-list" style="padding-top: 0;height: auto;">
    {if $order_list}
    {foreach from=$order_list item=order}
    <div class="block">
        <div class="order_list">
            <!--非当当自营显示店铺入口-->
            <div class="shop_title">
                <a href="">
                    <!--店铺名称-->
                    <div class="fl">
                        {$order.order_sn}
                    </div>
                    <span class="fr right_arrow"></span>
                </a>

            </div>
            <!--分包商品信息-->
            <div class="cart_item prd_ebook">
                <a href="order.php?act=detail&sn={$order.order_sn}">
                    <!--电子书加签-->
                    {foreach from=$order.order_detail item=od}
                    <!--包裹图片-->
                    <img src="{$od.img|build_url}" class="fl pro_pic">
                    {/foreach}
                    <!--包裹详情-->
                    <div class="detail">
                        <!--包裹状态-->
                        <div class="fr prd_state">
                            <!--状态文字-->
                            <div class="prd_state_title">
                                {$order.show_status}
                            </div>
                        </div>
                        <!--包裹名称显示，多件产品，显示包裹编号，一件产品显示产品名称-->
                        <p class="fl prd_tit">
                            {if count($order.order_detail) eq 1}
                            {$order.order_detail.0.name}
                            {else}
                            {/if}
                        </p>
                    </div>
                </a>
            <!--数量价格信息-->
            <div class="detail2">
                共<span>{count($order.order_detail)}</span>件商品
                <span>　总价：</span><span class="order_price">￥{$order.total_amount}</span>
            </div>
            <!--操作按键-->
            <div class="detail3">
                {if $order.status eq 6}
                <a href="order.php?act=express_info&order_sn={$order.order_sn}" onclick="show_mask()">查看物流</a>
                <a href="javascript:receive('{$order.order_sn}');" class="orange_hollow">确认收货</a>
                {/if}
                {if $order.status eq 1}
                <a href="javascript:pay_now('{$order.order_sn}');" class="orange_hollow">立即支付</a>
<!--                <a href="javascript:cancel_order('{$order.order_sn}');">取消订单</a>-->
                {/if}
            </div>
        </div>
        </div>
    </div>
    {/foreach}
    {else}
    <div class="block">
        <div class="empty-con">
            <span class="icon">&#xe623;</span>
            <span class="empty-tips">您还未订购过任何商品!</span>
            <span class="empty-btn">
                <a href="index.php" class="btn">去逛逛</a>
            </span>
        </div>
    </div>
    {/if}
</section>
<div style="height: 2.8rem;"></div>
<script type="text/javascript">
    $(function(){
        var status = {$status};
        $("#index_"+status).siblings().removeClass("hover")
        $("#index_"+status).addClass("hover");
    });

    function sort_order(mode) {
        var url = "order.php";
        var data = { "opera":"sort", "mode":mode };

        show_mask();
        $("#index_"+mode).siblings().removeClass("hover")
        $("#index_"+mode).addClass("hover");
        $.post(url, data, sort_order_handler, "json");
    }

    function sort_order_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#order-list").html(response.content);
        } else {
            show_message_dialog(response.msg);
        }
    }

    function comment(order_sn) {
        if(order_sn != '') {
            window.location.href = "order.php?act=comment&sn="+order_sn;
        }
    }

    function pay_now(order_sn) {
        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"pay_now", "order_sn":order_sn };

            show_mask();
            $.post(url, data, pay_now_handler, "json");
        }
    }

    function pay_now_handler(response) {
        if(response.error == 0) {
            wx.chooseWXPay({
                timestamp: response.timestamp,
                nonceStr: response.nonce_str,
                package: 'prepay_id='+response.prepay_id,
                signType: 'MD5',
                paySign: response.sign,
                success: function (res) {
                    // 支付成功后的回调函数
                    hide_mask();
                    if(res.errMsg == "chooseWXPay:ok") {
                        show_message_dialog("支付成功");
                        $("#dialog_close_btn,#dialog_close").click(function(){
                            window.location.reload();
                        });
                    } else {
                        show_message_dialog(res.errMsg+":支付失败");
                        $("#dialog_close_btn,#dialog_close").click(function(){
                            close_message_dialog();
                        });
                    }
                }
            });
        } else {
            hide_mask();
            show_message_dialog(response.msg);
        }
    }

    function cancel_order(order_sn) {
        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"cancel", "order_sn":order_sn };

            show_mask();
            $.post(url, data, cancel_order_handler, "json");
        }
    }

    function cancel_order_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#dialog_close_btn, #dialog_close").click(function () {
                window.location.reload();
            });
        }

        show_message_dialog(response.msg);
    }

    function receive(order_sn) {
        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"receive", "order_sn":order_sn };

            show_mask();
            $.post(url, data, receive_handler, "json");
        }
    }

    function receive_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#dialog_close_btn, #dialog_close").click(function () {
                window.location.reload();
            });
        }

        show_message_dialog(response.msg);
    }

    function rollback(order_sn) {
        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"rollback", "order_sn":order_sn };

            show_mask();
            $.post(url, data, receive_handler, "json");
        }
    }

    function rollback_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#dialog_close_btn, #dialog_close").click(function () {
                window.location.reload();
            });
        }

        show_message_dialog(response.msg);
    }

    {if is_weixin()}
    wx.config({
            appId: '{$signPackage.appId}',
            timestamp: {$signPackage.timestamp},
        nonceStr: '{$signPackage.nonceStr}',
        signature: '{$signPackage.signature}',
        jsApiList: [
        'chooseWXPay',
        'closeWindow'
    ]
    });
    {/if}
</script>
{/block}