{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>修改密码</em></h1>
</header>
{/block}
{block name="content"}
<!-- 修改密码页面 -->
<section class="register">
    <section class="register-con" id="step1">
        <div class="inp user bg">
            <span class="icon"></span>
            <span class="input">
                <input id="username" type="text" value="{substr($mobile, 0, 3)}***{substr($mobile, -4)}" placeholder="请输入你的手机号" disabled="disabled"/>
            </span>
            <span class="more"></span>
            <span class="clear" style="display: none;"></span>
        </div>
        <div class="pw_contain">
            <div class="inp graphics short small bg">
                <span class="input">
                    <input class="identify_code" type="text" placeholder="请输入图形验证码" id="pic_code"/>
                </span>
                <span class="clear" style="display: none;"></span>
            </div>
            <div class="identify">
                <a class="refresh" href="javascript:;" onclick="refresh_code();">refresh</a>
                <img class="repic" src="code.php" alt="验证码">
            </div>
        </div>
        <a class="btn" href="javascript:;" id="verify_pic_code">获取短信校验码</a>
    </section>

    <section class="register-con" id="step2" style="display: none;">
        <p class="title">已发送验证码到 {substr($mobile, 0, 3)}***{substr($mobile, -4)}</p>
        <div>
            <div class="inp user short small bg">
                <span class="input">
                    <input type="text" id="verify" placeholder="请输入验证码">
                </span>
                <span class="clear" style="display: none;"></span>
            </div>
            <button id="reget" class="" type="button" on="获取验证码" off="重新获取" time="60">
                <em>重新获取</em><i id="timer">39</i>
            </button>
        </div>
        <a class="btn" href="javascript:;" id="verify_message_code">下一步</a>
    </section>

    <section class="register-con" id="step3" style="display: none;">
        <p class="title">请设置新密码：</p>
        <div class="pw_contain">
            <div class="inp pw bg nomar">
                <span class="icon"></span>
                <span class="input">
                    <input id="password" type="password" name="password" placeholder="密码：6-20位字母或数字"/>
                </span>
                <span class="clear" style="display: none;"></span>
            </div>
        </div>
        <a class="btn" href="javascript:void(0);" id="set_password">设置新密码</a>
    </section>
</section>

<script type="text/javascript">
    var interval = null;
    var timer = 0;
    var mobile = "{$mobile}";

    $(function(){
        $("#verify_pic_code").click(function(){
            verify_pic_code();
        });

        $("#verify_message_code").click(function(){
            verify_message_code();
        });

        $("#reget").click(function(){
            get_message_code();
        });

        $("#set_password").click(function(){
            set_password();
        });

        if(mobile == "") {
            show_operation_dialog("confirm_dialog");
            $("#confirm-message").text("您尚未设置密码,请先设置");
            $("#dialog_confirm_btn").text("现在设置");
            $("#dialog_confirm_btn").click(function(){
                close_operation_dialog();
            });
            $("#dialog_confirm_cancel").text("暂不设置");
            $("#dialog_confirm_cancel").click(function(){
                window.history.back();
            });
        }
    });

    function back() {
        window.history.back();
        window.location.reload();
    }

    function show_operation_dialog(id) {
        if(id == undefined) {
            id = "dialog";
        }
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#"+id).show();
    }

    function close_operation_dialog(id) {
        if(id == undefined) {
            id = "dialog";
        }
        $(".cd-popup").removeClass("is-visible");
        $("#"+id).hide();
    }

    function verify_pic_code() {
        var code = $("#pic_code").val();

        if(code == "") {
            show_message_dialog("请输入图形验证码");
            return false;
        }

        var url = "data_center.php";
        var data = { "opera":"verify_pic_code", "code":code };

        show_mask();
        $.post(url, data, verify_pic_code_handler, "json");
    }

    function verify_pic_code_handler(response) {
        hide_mask();
        if(response.error == 0) {
            step(2);
            get_message_code();
        } else {
            show_message_dialog(response.msg);
        }
    }

    function verify_message_code() {
        var code = $("#verify").val();

        if(code == "") {
            show_message_dialog("请输入验证码");
            return false;
        }

        var url = "data_center.php";
        var data = { "opera":"verify_message_code", "code":code, "mobile": mobile };

        show_mask();
        $.post(url, data, verify_message_code_handler, "json");
    }

    function verify_message_code_handler(response) {
        hide_mask();
        if(response.error == 0) {
            step(3);
        } else {
            show_message_dialog(response.msg);
        }
    }

    function set_password() {
        var password = $("#password").val();

        if(password == "") {
            show_message_dialog("请输入新密码");
            return false;
        } else {
            var url = "password.php";
            var data = { "opera":"set", "password":password };

            show_mask();
            $.post(url, data, set_password_handler, "json");
        }
    }

    function set_password_handler(response) {
        hide_mask();
        show_message_dialog(response.msg);
        if(response.error == 0) {
            $("#dialog_close_btn").click(function(){
                window.history.back();
            });

            $("#dialog_close").click(function(){
                window.history.back();
            });
        }
    }

    function get_message_code() {
        if(timer == 0) {
            var url = "data_center.php";
            var data = { "opera":"get_message_code", "mobile": mobile };

            show_mask();
            $.post(url, data, get_message_code_handler, "json");
        }
    }

    function get_message_code_handler(response) {
        if(response.error == 0) {
            timer = response.timer;
            $("#reget").removeClass("new");
            $("#reget").html("<em>重新获取</em><i id='timer'>"+timer+"</i>");
            interval = setInterval(trick, 1000);
            show_message_dialog("当前没有短信接口,请输入验证码："+response.code);
        } else {
            show_message_dialog(response.msg);
            if(response.timer != undefined) {
                timer = response.timer;
                $("#reget").removeClass("new");
                $("#reget").html("<em>重新获取</em><i id='timer'>" + timer + "</i>");
                interval = setInterval(trick, 1000);
            }
        }
    }

    function trick() {
        if(timer) {
            timer--;
            $("#timer").text(timer);
        } else {
            clearInterval(interval);
            $("#reget").addClass("new");
            $("#reget").html("<em>获取短信验证码</em>");
        }
    }

    function step(num) {
        $(".register-con").hide();
        $("#step"+num).show();
        if(num > 1) {
            num--;
            $(".back").click(function(){
                step(num);
                return false;
            });
        } else {
            $(".back").click(function(){
                return true;
            });
        }
    }

    function refresh_code() {
        $(".repic").attr("src", "code.php?rand="+Math.random()*1000);
    }
</script>
{/block}
{block name="footer"}
{/block}