<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>{$title}</em></h1>
</header>
<!-- 我的积分 -->
<section class="points">
    <header class="points-header">
        <!-- 积分基本信息 -->
        <section class="points-basic">
            <h3 class="points-count"><em>{$user_info[{$mode}]}</em>{$unit}<a href="#">使用帮助</a></h3>
            <p>{$notice}</p>
        </section>
        <nav>
            <div><a href="javascript:alert('敬请期待');"><i class="icon">&#xe633;</i>领</a></div>
            <div><a href="javascript:alert('敬请期待');"><i class="icon">&#xe632;</i>花</a></div>
        </nav>
    </header>
    <div class="points-detail">
        <a class="slide-link" href="#">
            收支明细
        </a>
        <ul>
            {foreach from=$member_exchange item=exchange}
            <li>
                {$exchange.remark}
                <em {if $exchange[{$mode}] gt 0}class="plus"{/if}>{if $exchange[{$mode}] gt 0}+{/if}{$exchange[{$mode}]}</em>
                <p>{date("Y-m-d H:i:s", $exchange.add_time)}</p>
            </li>
            {/foreach}
        </ul>
    </div>
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.php"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="user.php"><em class="icon">&#xe604;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
</body>
</html>
