{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>{$title}</em></h1>
</header>
{/block}
{block name="content"}
<!-- 我的积分 -->
<section class="points">
    <header class="points-header">
        <!-- 积分基本信息 -->
        <section class="points-basic">
            <h3 class="points-count"><em>{$user_info[{$mode}]}</em>{$unit}
<!--        <a href="#">使用帮助</a>-->
            </h3>
            <p>{$notice}</p>
        </section>
        <!--
        <nav>
            <div><a href="javascript:alert('敬请期待');"><i class="icon">&#xe627;</i>领</a></div>
            <div><a href="javascript:alert('敬请期待');"><i class="icon">&#xe626;</i>花</a></div>
        </nav>
        -->
    </header>
    <div class="points-detail">
        <a class="slide-link" href="#">
            收支明细
        </a>
        <ul>
            {foreach from=$member_exchange item=exchange}
            <li>
                {$exchange.remark}
                <em {if $exchange[{$mode}] gt 0}class="plus"{/if}>{if $exchange[{$mode}] gt 0}+{/if}{$exchange[{$mode}]}</em>
                <p>{date("Y-m-d H:i:s", $exchange.add_time)}</p>
            </li>
            {/foreach}
        </ul>
    </div>
</section>
<div style="height: 2.2rem;"></div>
{/block}
{block name="footer"}
{/block}