{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:back();" class="back"></a>
    <h1><em>{$product.name}</em></h1>
</header>
{/block}
{block name="content"}
<!-- 产品图片轮播区 -->
<section id="focus" class="focus">
    <div class="hd">
        <ul></ul>
    </div>
    <div class="bd">
        <ul>
            {foreach from=$product.gallery item=gallery}
            <li><a href="#"><img _src="{$gallery|build_url}" src="{$template_dir}images/blank.png" style="height: auto;"/></a></li>
            {/foreach}
        </ul>
    </div>
</section>
<!-- 产品详情页 -->
<section class="product-detail">
    <article>{$product.name}</article>
    <div class="left">
        {if $product.integral gt 0}
        <b><span id="main_price">{sprintf("%.2f", $product.integral)}积分</span></b>
        {else}
        <b>￥<span id="main_price">{sprintf("%.2f", $product.price)}</span></b>
        {/if}
    </div>
    <div class="right">
        <ul>
            <li class="share"><a href="javascript:;" onclick="document.getElementById('mcover').style.display='block';">分享</a></li>
        </ul>
    </div>
    <div id="mcover" onclick="document.getElementById('mcover').style.display='';" style="display: none;">
        <img src="{$template_dir}images/guide.png">
    </div>
</section>

<!-- 数量开始 -->

<section class="quantity">
    <h4>数量：</h4>
    <div class="number_con fl">
        <span class="minus" id="minus">-</span>
        <div class="input"><input id="buy_num" name="buy_num" type="tel" value="1"></div>
        <span class="plus on" id="plus">+</span>
    </div>
</section>

<!-- 产品详情 -->
<section class="detail-con">
    <a class="arrow_con title">
        <div class="arrow_d">商品详情</div>
    </a>
    <section id="detail-con" style="display: none;">
        <div class="detail-content">
            {str_replace('src="/upload','src="http://www.dupenda.cn/upload', $product.desc)}
        </div>
    </section>
</section>
<div style="height: 2.49rem;">&nbsp;</div>
<!-- 产品页底部 -->
<!-- 产品页底部 -->
<section class="actionBar-container">
    <div class="action-bar mui-flex">
        <button class="cart cell" id="add_to_cart_btn" style="margin-bottom: 0;">加入购物车</button>
        <button class="buy cell" id="buy_now_btn">立即购买</button>
    </div>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery.lazyload.min.js"></script>
<script type="text/javascript">
    var hour = 0;
    var min = 0;
    var second = 0;
    var interval = null;

    function back() {
        if(document.referer == "" || document.referer == undefined) {
            window.location.href = "index.php";
        } else {
            window.history.back();
        }
    }

    $(function() {
        $("img.lazy").lazyload({
            effect : "fadeIn"
        });
        $(".option .arrow_con").click(function(){
            toggle_option_bar();
        });
        $(".option_detail ul li").click(function(){
            $(this).siblings().removeClass("on");
            $(this).addClass("on");
        });

        $(".detail-con .arrow_con").click(function(){
            if($(".detail-con .arrow_d").hasClass("up")){
                $("#detail-con").slideUp();
                $(".detail-con .arrow_d").removeClass("up");
            }else{
                $("#detail-con").slideDown();
                $(".detail-con .arrow_d").addClass("up");
            }
        })

        $("#buy_num").blur(function(){
            var buy_num = $(this).val();

            buy_num = parseInt(buy_num);

            if(isNaN(buy_num) || buy_num <= 0)
            {
                buy_num = 1;
            }

            $(this).val(buy_num);
        });
    });

    function trick() {
        if(hour == 0 && min == 0 && second == 0) {
            $(".promote").hide();
            clearInterval(interval);
        } else {
            if(second > 0) {
                second--;
            } else {
                if(min > 0) {
                    second = 59;
                    min--;
                } else {
                    if(hour > 0) {
                        min = 59;
                        hour--;
                    }
                }
            }

            $("#hour").text(hour);
            $("#min").text(min);
            $("#second").text(second);
        }
    }

    function toggle_option_bar() {
        if($(".option .arrow_d").hasClass("up")){
            $(".option_detail").slideUp();
            $(".option .arrow_d").removeClass("up");
        }else{
            $(".option_detail").slideDown();
            $(".option .arrow_d").addClass("up");
        }
    }
</script>
<script type="text/javascript" src="{$template_dir}js/TouchSlide.1.1.js"></script>
<script type="text/javascript">
    var operation = 0;

    function add_to_cart(product_sn) {
        var url = "cart.php";
        var buy_num = parseInt($("#buy_num").val());

        if(isNaN(buy_num) || buy_num <= 0) {
            show_message_dialog("请输入购买数量");
            return false;
        }

        var data = { "opera":"add", "product_sn": product_sn, "number": buy_num };
        show_mask();
        $.post(url, data, add_to_cart_handler, "json");
    }

    function add_to_cart_handler(response) {
        if(response.error == 0) {
            show_operation_dialog();
            $("#dialog_confirm_btn").text("继续逛逛");
            $("#dialog_confirm_cancel").text("前往结算");
            $("#confirm-message").text("加入购物车成功");

            $("#dialog_confirm_btn").click(function(){
                close_operation_dialog();
            });

            $("#dialog_confirm_cancel").click(function(){
                window.location.href = "cart.php";
            });
        } else {
            show_message_dialog(response.msg);
            if(response.error == 2) {
                $("#dialog_close_btn").click(function(){
                    window.location.href = "login.php";
                });

                $("#dialog_close").click(function(){
                    window.location.href = "login.php";
                });
            }
        }
    }

    function buy_now(product_sn) {
        var url = "cart.php";
        var buy_num = parseInt($("#buy_num").val());

        if(isNaN(buy_num) || buy_num <= 0) {
            show_message_dialog("请输入购买数量");
            return false;
        }

        var data = { "opera":"add", "product_sn": product_sn, "number": buy_num };
        show_mask();
        $.post(url, data, buy_now_handler, "json");
    }

    function buy_now_handler(response) {
        if(response.error == 0) {
            window.location.href= "cart.php";
        } else {
            show_message_dialog(response.msg);
            if(response.error == 2) {
                $("#dialog_close_btn").click(function(){
                    window.location.href = "login.php";
                });

                $("#dialog_close").click(function(){
                    window.location.href = "login.php";
                });
            }
        }
    }

    function plus() {
        var buy_num = $("#buy_num").val();

        buy_num = parseInt(buy_num);
        if(isNaN(buy_num) || buy_num <= 0) {
            minus_disable();
            $("#buy_num").val(1);
        } else {
            buy_num++;
            $("#buy_num").val(buy_num);
            minus_disable();
            minus_enable();
        }
    }

    function minus() {
        var buy_num = $("#buy_num").val();

        buy_num = parseInt(buy_num);
        if(isNaN(buy_num) || buy_num <= 1) {
            minus_disable();
            $("#buy_num").val(1);
        } else {
            buy_num--;
            $("#buy_num").val(buy_num);
            if(buy_num <= 1) {
                minus_disable();
            }
            plus_disable();
            plus_enable();
        }
    }

    function minus_enable() {
        $("#minus").addClass("on");
        $("#minus").bind("click", minus);
    }

    function minus_disable() {
        $("#minus").removeClass("on");
        $("#minus").unbind("click");
    }

    function plus_enable() {
        $("#plus").addClass("on");
        $("#plus").bind("click", plus);
    }

    function plus_disable() {
        $("#plus").removeClass("on");
        $("#plus").unbind("click");
    }

    TouchSlide({
        slideCell:"#focus",
        titCell:".hd ul", //开启自动分页 autoPage:true ，此时设置 titCell 为导航元素包裹层
        mainCell:".bd ul",
        effect:"left",
        autoPlay:false,//自动播放
        autoPage:true, //自动分页
        switchLoad:"_src" //切换加载，真实图片路径为"_src"
    });

    $(function(){
        var options = $(".option_detail");
        var options_values = options.children().children("li");
        options_values.each(function(i, e) {
            e.onclick = function() {
                select_attribute(this);
            }
        });

        $("#plus").bind("click", plus);
        $("#minus").bind("click", minus);

        $("#collection_btn").bind("click", function() { collection("{$product.product_sn}"); });
        $("#distribution_btn").bind("click", function() { distribution_confirm("{$product.product_sn}"); });

        $("#add_to_cart_btn").bind("click", function() { add_to_cart("{$product.product_sn}"); });
        $("#buy_now_btn").bind("click", function() { buy_now("{$product.product_sn}"); });

        $(".detail-content").children("img").each(function (i, e){
            $(this).attr("width", "100%");
        });
    });
</script>
<script type="text/javascript" src="{$template_dir}js/jquery.lazyload.min.js"></script>
<script type="text/javascript">
    $(function() {
        $("img.lazy").lazyload({
            effect : "fadeIn"
        });
    });
</script>
<script type="text/javascript">
    TouchSlide({
        slideCell:"#focus",
        titCell:".hd ul", //开启自动分页 autoPage:true ，此时设置 titCell 为导航元素包裹层
        mainCell:".bd ul",
        effect:"left",
        autoPlay:true,//自动播放
        autoPage:true, //自动分页
        switchLoad:"_src" //切换加载，真实图片路径为"_src"
    });
</script>
{if is_weixin()}
<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.1.0.js"></script>
<script type="text/javascript">
    wx.config({
            appId: '{$signPackage.appId}',
            timestamp: {$signPackage.timestamp},
            nonceStr: '{$signPackage.nonceStr}',
            signature: '{$signPackage.signature}',
            jsApiList: [
                'chooseWXPay',
                'closeWindow',
                'onMenuShareTimeline',
                'onMenuShareAppMessage',
                'onMenuShareQQ',
                'onMenuShareWeibo',
                'onMenuShareQZone'
            ]
    });

    wx.ready(function() {
        var share_title = '我在{$config.site_name}淘到一款好产品，快来看哦';
        var share_link = '{$recommend_url}';
        var share_img = '{$config.domain}{$product.img}';
        var share_desc = '{$product.desc}';
        //分享到朋友圈
        wx.onMenuShareTimeline({
            title: share_title, // 分享标题
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享到朋友圈成功了呢!");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("为什么要取消分享呢，不喜欢人家了吗？");
            }
        });

        //分享给朋友
        wx.onMenuShareAppMessage({
            title: share_title, // 分享标题
            desc: share_desc, // 分享描述
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            type: 'link', // 分享类型,music、video或link，不填默认为link
            dataUrl: '', // 如果type是music或video，则要提供数据链接，默认为空
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享给朋友成功了哦！");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("喜欢我就把我推荐给你的朋友嘛~~");
            }
        });

        //分享到QQ
        wx.onMenuShareQQ({
            title: share_link, // 分享标题
            desc: share_desc, // 分享描述
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享到QQ成功！");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("听说颜值高的人都会把我分享出去的哦");
            }
        });

        //分享到腾讯微博
        wx.onMenuShareWeibo({
            title: share_title, // 分享标题
            desc: share_desc, // 分享描述
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享到腾讯微博成功!");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("把我分享到微博去玩玩嘛~");
            }
        });

        //分享到QQ空间
        wx.onMenuShareQZone({
            title: share_title, // 分享标题
            desc: share_desc, // 分享描述
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享到QQ空间成功");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("人家想去QQ空间看看啦~");
            }
        });
    });
</script>
{/if}
{/block}
{block name="footer"}
{/block}