<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="css/mobile.css">
    <link rel="stylesheet" href="css/fonts.css">
</head>
<body>
<header class="header" style="position:fixed">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>商品列表</em></h1>
</header>

<!-- 筛选开始 -->
<section class="filter">
    <ul>
        <li class="on"><a href="#"><em>销量</em></a></li>
        <li><a href="#"><em>价格</em></a></li>
        <li><a href="#"><em>折扣</em></a></li>
        <li><a href="#"><em>好评</em></a></li>
        <li><a href="#"><em>最新</em></a></li>
    </ul>
</section>
<!-- 内容开始 -->
<section class="product-list">
    <ul>
        <li>
            <a href="#">
                <img class="lazy" src="images/bg_pic.png" data-original="http://img32.ddimg.cn/71/24/1145039912-1_b.jpg" alt=" 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 ">
                <dl class="arrow">
                    <dt> 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 </dt>
                    <dd>￥69.00</dd>
                </dl>
            </a>
        </li>
        <li>
            <a href="#">
                <img class="lazy" src="images/bg_pic.png" data-original="http://img32.ddimg.cn/71/24/1145039912-1_b.jpg" alt=" 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 ">
                <dl class="arrow">
                    <dt> 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 </dt>
                    <dd>￥69.00</dd>
                </dl>
            </a>
        </li>
        <li>
            <a href="#">
                <img class="lazy" src="images/bg_pic.png" data-original="http://img32.ddimg.cn/71/24/1145039912-1_b.jpg" alt=" 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 ">
                <dl class="arrow">
                    <dt> 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 </dt>
                    <dd>￥69.00</dd>
                </dl>
            </a>
        </li>
        <li>
            <a href="#">
                <img class="lazy" src="images/bg_pic.png" data-original="http://img32.ddimg.cn/71/24/1145039912-1_b.jpg" alt=" 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 ">
                <dl class="arrow">
                    <dt> 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 </dt>
                    <dd>￥69.00</dd>
                </dl>
            </a>
        </li>
        <li>
            <a href="#">
                <img class="lazy" src="images/bg_pic.png" data-original="http://img32.ddimg.cn/71/24/1145039912-1_b.jpg" alt=" 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 ">
                <dl class="arrow">
                    <dt> 初语 2015夏季新品  文艺蝙蝠袖 字母印花倒梯形短袖T恤 女8520131968 </dt>
                    <dd>￥69.00</dd>
                </dl>
            </a>
        </li>
    </ul>
</section>

<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="js/jquery.lazyload.min.js"></script>
<script type="text/javascript">
    $(function() {
        $("img.lazy").lazyload({
            effect : "fadeIn"
        });
    });
</script>
</body>
</html>
