<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>会员推广名片</em></h1>
</header>
<!-- 推广名片页面 -->
<section class="qr-card">
    <section class="qr-card-con">
        <div class="card-header">
            <img src="{if $user_info.headimg neq ""}{$user_info.headimg}{else}{$template_dir}images/wang.jpg{/if}" alt="{$user_info.nickname}"/>
            <div class="card-header-con">
                <span class="icon">&#xe637;</span>
                <span>我是{$user_info.nickname}，</span>
                <span>关注健康、关注养生都在<em style="color: #e60012;font-size: .8rem;">{$config.site_name}</em>！</span>
            </div>
        </div>
        <div class="card-img">
            <img src="{if $qrcode}{$qrcode}{else}{$template_dir}images/qrcode.jpg{/if}" alt="推广二维码"/>
        </div>
        <div class="card-footer">
            <div class="card-tips">
                <span>长按此图，识别二维码，添加关注。</span>
                <span>怪我会读心咯！</span>
                <span>总能找到你最喜欢的平台。</span>
            </div>
            <div class="card-logo">
                {$config.site_name}
            </div>
        </div>
    </section>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
