{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>{$config.site_name}</em></h1>
</header>
{/block}
{block name="content"}
<!-- 推广名片页面 -->
<section class="qr-card">
    <section class="qr-card-con">
        <div class="card-header">
            <img src="{if $member_info.wx_headimg neq ""}{$member_info.wx_headimg}{else}{$template_dir}images/wang.jpg{/if}" alt="{$member_info.wx_nickname}"/>
            <div class="card-header-con">
                <span class="icon">&#xe637;</span>
                <span>我是{$member_info.wx_nickname}，</span>
                <span>补水 舒缓 控油 提神 定妆 尽在:<em style="color: #e60012;font-size: .8rem;">{$config.site_name}</em>！</span>
            </div>
        </div>
        <div class="card-img">
            <img src="{if $qrcode}{$qrcode}{else}http://open.weixin.qq.com/qr/code/?username={$config.wechat_account}{/if}" alt="推广二维码"/>
        </div>
        <div class="card-footer">
            <div class="card-tips">
                <span>长按此图，识别二维码，添加关注。</span>
            </div>
            <div class="card-logo">
                {$config.site_name}
            </div>
        </div>
    </section>
</section>
{/block}
{block name="footer"}
{/block}