{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>{$config.site_name}</em></h1>
</header>
{/block}
{block name="content"}
<!-- 推广名片页面 -->
<section class="qr-card">
    <section class="qr-card-con">
        <div class="card-header">
            <img src="{if $member_info.wx_headimg neq ""}{$member_info.wx_headimg}{else}{$template_dir}images/wang.jpg{/if}" alt="{$member_info.wx_nickname}"/>
            <div class="card-header-con">
                <span class="icon">&#xe637;</span>
                <span>我是{$member_info.wx_nickname}，</span>
                <span>知识 财富 一切尽在:<em style="color: #e60012;font-size: .8rem;">{$config.site_name}</em>！</span>
            </div>
        </div>
        <div class="card-img">
            <img src="{if $qrcode}{$qrcode}{else}http://open.weixin.qq.com/qr/code/?username={$config.wechat_account}{/if}" alt="推广二维码"/>
        </div>
        <div class="card-footer">
            <div class="card-tips">
                <span>长按此图，识别二维码，添加关注。</span>
            </div>
            <div class="card-logo">
                {$config.site_name}
            </div>
        </div>
    </section>
</section>
{/block}
{block name="footer"}
{if is_weixin()}
<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.1.0.js"></script>
<script type="text/javascript">
    wx.config({
            appId: '{$signPackage.appId}',
            timestamp: {$signPackage.timestamp},
        nonceStr: '{$signPackage.nonceStr}',
        signature: '{$signPackage.signature}',
        jsApiList: [
        'chooseWXPay',
        'closeWindow',
        'onMenuShareTimeline',
        'onMenuShareAppMessage',
        'onMenuShareQQ',
        'onMenuShareWeibo',
        'onMenuShareQZone'
    ]
    });

    wx.ready(function() {
        var share_title = '我在{$config.site_name}学知识，赚财富哦，快一起来吧';
        var share_link = '{$recommend_url}';
        var share_img = '{$member_info.wx_headimg}';
        var share_desc = '快来看看哦';
        //分享到朋友圈
        wx.onMenuShareTimeline({
            title: share_title, // 分享标题
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享到朋友圈成功了呢!");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("为什么要取消分享呢，不喜欢人家了吗？");
            }
        });

        //分享给朋友
        wx.onMenuShareAppMessage({
            title: share_title, // 分享标题
            desc: share_desc, // 分享描述
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            type: 'link', // 分享类型,music、video或link，不填默认为link
            dataUrl: '', // 如果type是music或video，则要提供数据链接，默认为空
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享给朋友成功了哦！");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("喜欢我就把我推荐给你的朋友嘛~~");
            }
        });

        //分享到QQ
        wx.onMenuShareQQ({
            title: share_link, // 分享标题
            desc: share_desc, // 分享描述
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享到QQ成功！");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("听说颜值高的人都会把我分享出去的哦");
            }
        });

        //分享到腾讯微博
        wx.onMenuShareWeibo({
            title: share_title, // 分享标题
            desc: share_desc, // 分享描述
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享到腾讯微博成功!");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("把我分享到微博去玩玩嘛~");
            }
        });

        //分享到QQ空间
        wx.onMenuShareQZone({
            title: share_title, // 分享标题
            desc: share_desc, // 分享描述
            link: share_link, // 分享链接
            imgUrl: share_img, // 分享图标
            success: function () {
                // 用户确认分享后执行的回调函数
                show_message_dialog("分享到QQ空间成功");
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
                show_message_dialog("人家想去QQ空间看看啦~");
            }
        });
    });
</script>
{/if}
{/block}