{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我要充值</em></h1>
    <a href="recharge.php?act=list" class="edit">查看</a>
</header>
{/block}
{block name="content"}
<!-- 我要充值 -->
<section class="recharge">
    <div class="recharge-con">
        <div class="recharge-tips">
            <i class="icon">&#xe613;</i>充值金额将充入到余额款项中,充值金额不允许提现。
        </div>
        <div class="recharge-value">
            <label><span>充值金额：</span><input type="number" value="" placeholder="请填写金额（元）" id="amount"></label>
            <label>
                <ul class="paydetail" style="padding:.5rem .8rem .5rem 0;">
                    <li>支付方式：
                        {foreach from=$payment_list item=payment}
                        <span onclick="change_payment({$payment.id});">{$payment.name}</span>
                        {/foreach}
                    </li>
                </ul>
            </label>
        </div>
        <div class="recharge-info" id="payment_info">
        </div>
        <div class="recharge-btn">
            <a class="btn" href="javascript:void(0);" onclick="submit_recharge();">确认充值</a>
        </div>
    </div>
</section>
<div style="height: 2.2rem;"></div>
{if is_weixin()}
<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.1.0.js"></script>
{/if}
<script type="text/javascript">
    var global_result = null;
    var payment_plugins = "";
    var payment_list = {$payment_list_json};

    $(function() {
        $(".paydetail li span").click(function(){
            $(this).siblings().removeClass("on");
            $(this).addClass("on");
        })
    });

    function change_payment(id) {
        if(payment_list[id] != undefined) {
            payment_plugins = payment_list[id].plugins;
            $("#payment_info").html(payment_list[id].detail);
        } else {
            $("#payment_info").html("");
            payment_plugins = "";
        }
    }

    function submit_recharge() {
        var amount = parseFloat($("#amount").val());
        var msg = "";

        if(isNaN(amount) || amount <= 0) {
            msg += "-请填写充值金额<br/>";
        }

        if(payment_plugins == "") {
            msg += "-请选择支付方式<br/>";
        }

        if(msg != "") {
            show_message_dialog(msg);
        } else {
            if(payment_plugins == "Wechat") {
                get_prepay_id();
            } else {
                var data = { "opera":"bank", "amount":amount };
                var url = "recharge.php";

                show_mask();
                $.post(url, data, submit_recharge_handler, "json");
            }
        }
    }

    function submit_recharge_handler(result) {
        hide_mask();
        if(result.error == 0) {
           show_message_dialog(result.msg);
        } else {
            show_message_dialog(result.msg);
        }
    }

    function get_prepay_id() {
        var amount = $("#amount").val();
        amount = parseFloat(amount);

        if(isNaN(amount) || amount <= 0) {
            show_message_dialog("充值金额必须大于0");
            return false;
        }

        var data = { "opera":"wechat", "amount":amount };
        var url = "recharge.php";

        show_mask();
        $.post(url, data, get_prepay_id_handler, "json");
    }

    function get_prepay_id_handler(result) {
        hide_mask();
        if(result.error == 0) {
            global_result = result;
            wx.chooseWXPay({
                timestamp: global_result.timestamp,
                nonceStr: global_result.nonce_str,
                package: 'prepay_id='+global_result.prepay_id,
                signType: 'MD5',
                paySign: global_result.sign,
                success: function (res) {
                    // 支付成功后的回调函数
                    if(res.errMsg == "chooseWXPay:ok") {
                        show_message_dialog("充值成功");
                    } else {
                        show_message_dialog(res.errMsg+":支付失败");
                    }
                }
            });
        } else {
            show_message_dialog(result.msg);
        }
    }

    {if is_weixin()}
        wx.config({
            appId: '{$signPackage.appId}',
            timestamp: {$signPackage.timestamp},
            nonceStr: '{$signPackage.nonceStr}',
            signature: '{$signPackage.signature}',
            jsApiList: [
                'chooseWXPay',
                'closeWindow'
            ]
        });
    {/if}
</script>
{/block}
{block name="footer"}
{/block}