<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>卡券详情</em></h1>
</header>
<!-- 确定订单 -->
<section class="orderdetail-con">
    <!-- 订单状态 -->
    <section class="order-status border_bottom">
        <div class="status-title red-font"><i class="icon">&#xe629;</i> &nbsp;卡券状态：{$order_content.show_status}</div>
        {if $order_content.status eq 0}
        <a href="#">
            <div class="status-con">
                <div class="status-content">
                    <span>您的卡券还有{$order_content.left_time}到期，别忘了去体验哦~</span>
                </div>
            </div>
        </a>
        {/if}
    </section>
    <!-- 订单产品详情 -->
    <section class="orders">
        <div class="w_panel border_lr order_main border_top rarrow">
            <h4 class="h_title">
                <i class="icon">&#xe610;</i>&nbsp;{$shop.shop_name}
            </h4>
        </div>
        <div class="border_lr trans_div order_action_block border_bottom">
            <div>
                <div class="single_line_div border_0 leavemessage">
                    订单编号：{$order_content.order_sn}
                </div>
                <div>
                    <ul class="product_ul">
                        <li>
                            <div class="box">
                                <div class="product_cover">
                                    <img width="100%" src="{$product_info.img}">
                                </div>
                                <div class="product_info cr_2">
                                    <p class="product_name">{$order_content.product_name}</p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <hr color="#E5E5E5" class="line_l" size="1">
                <div class="single_line_div border_0 leavemessage">
                    消费代码：{$order_content.code}
                </div>
            </div>
        </div>
        <!-- 产品详情 -->
        <section class="detail-con">
            <a class="arrow_con title">
                <div class="arrow_d">商品详情</div>
            </a>
            <section id="detail-con">
                <div class="detail-content">
                    {$product_info.detail}
                </div>
            </section>
        </section>
    </section>
    <section class="shop-stat">
        <a href="tel:{$shop.mobile}"><em class="icon">&#xe600;</em>联系商家</a>
        {if $shop.latitude neq '' and $shop.longitude neq ''}
        <a href="http://api.map.baidu.com/marker?location={$shop.latitude},{$shop.longitude}&title={$shop.shop_name}&content=&output=html"><em class="icon">&#xe61a;</em>到这里去</a>
        {/if}
        <a href="shop.php?sn={$order_content.business_account}"><em class="icon">&#xe610;</em>进店逛逛</a>
    </section>
    <div style="height: 60px;"></div>
</section>
</body>
</html>
