{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我的团队</em></h1>
</header>
{/block}

{block name="content"}
<!-- 内容开始 -->
<section class="myteam">
    {foreach from=$member_list item=member name=member_list}
    <section class="myteam-con">
        <div class="myteam-header">
            <div class="myteam-header-info">
                <img src="{if $member.wx_headimg neq ""}{$member.wx_headimg}{else}{$template_dir}images/wang.jpg{/if}" alt="{$member.wx_nickname}" />
                <span>{$member.wx_nickname}</span>
                <em>{$member.account}</em>
                <em>{$member.mobile}</em>
                <em>{$lang.level[$member.level_id]}</em>
            </div>
        </div>
    </section>
    {/foreach}
</section>

<script type="text/javascript" src="{$template_dir}js/jquery.lazyload.min.js"></script>
<script type="text/javascript">
    $(function() {
        $("img.lazy").lazyload({
            effect : "fadeIn"
        });
    });
</script>
{/block}
{block name="footer"}
{/block}