{extends file="index.phtml"}
{block name="header"}
{/block}
{block name="content"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>订单支付</em></h1>
</header>
<!-- 支付详情 -->
<section class="paycon border_bottom">
    <div class="paydetail">
        <ul>
            <li>支付订单：{$order.order_sn}</li>
            <li>订单类型：{$lang.order_type[$order.type]}</li>
            <li>订单详情：</li>
            {foreach from=$order_detail item=od}
            <li>{$od.name}x{$od.number}</li>
            {/foreach}
            <li>支付金额：<i class="red_money">{sprintf("%.2f", $order.total_amount)}元</i></li>
            <li>支付方式：
                {foreach from=$payment_list item=payment}
                {if $payment.plugins eq 'Wechat'}
                <span onclick="get_pay_link('{$payment.plugins}');" data-plugin="{$payment.plugins}"><em class="icon">&#xe60f;</em>{$payment.name}</span>
                {else}
                <span onclick="get_pay_link('{$payment.plugins}');" data-plugin="{$payment.plugins}"><em class="icon">&#xe623;</em>{$payment.name}</span>
                {/if}
                {/foreach}
            </li>
        </ul>
    </div>
    <div id="payment-desc" class="article-con">

    </div>
    <div class="paybtn-con">
        <a href="javascript:topay();" class="paybtn" id="pay_btn">确认支付</a>
    </div>
</section>
<script type="text/javascript">
    var global_result = null;
    var payment_list = {$payment_list_json};
    var payment_plugin = '';

    $(function() {
        $(".paydetail ul li span").click(function(){
            $(this).siblings().removeClass("on");
            $(this).addClass("on");
            payment_plugin = $(this).attr('data-plugin');
        })
    });

    function topay() {
        if($(this).hasClass('disabled')) {
            return false;
        }

        get_prepay_id();

//        show_message_dialog("等待支付接口申请下来");
    }

    function get_pay_link(plugins) {
        switch(plugins)
        {
            case "Wechat":
//                get_prepay_id();
                $('#pay_btn').removeClass('disabled');
                $('#payment-desc').html('');
                break;
            default:
                $('#pay_btn').addClass('disabled');
//                show_message_dialog("该支付方式暂无接口支持");
                for(var i in payment_list) {
                    var payment_tmp = payment_list[i];
                    if(payment_tmp.plugins == plugins) {
                        $('#payment-desc').html(payment_tmp.desc + '<br/>' + payment_tmp.detail.split('</label>').join('</label><br/>'));
                    }
                }
                break;
        }
    }

    function get_prepay_id() {
        var data = { "opera":"wechat" };
        var url = "topay.php";

        show_mask();
        $.post(url, data, get_prepay_id_handler, "json");
    }

    function get_prepay_id_handler(result) {
        hide_mask();
        if(result.error == 0) {
            global_result = result;
            $("#pay_btn").bind("click", function() {
                wx.chooseWXPay({
                    timestamp: result.timestamp,
                    nonceStr: result.nonce_str,
                    package: 'prepay_id='+result.prepay_id,
                    signType: 'MD5',
                    paySign: result.sign,
                    success: function (res) {
                        // 支付成功后的回调函数
                        if(res.errMsg == "chooseWXPay:ok") {
                            window.location.href = "payresult.php";
                        } else {
                            show_message_dialog(res.errMsg+":支付失败");
                        }
                    }
                });
            });
        } else {
            show_message_dialog(result.msg);
        }
    }

    {if is_weixin()}
        wx.config({
            appId: '{$signPackage.appId}',
            timestamp: {$signPackage.timestamp},
            nonceStr: '{$signPackage.nonceStr}',
            signature: '{$signPackage.signature}',
            jsApiList: [
                'chooseWXPay',
                'closeWindow'
            ]
        });
    {/if}
</script>
{/block}
{block name="footer"}{/block}