{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>查看物流</em></h1>
</header>
{/block}
{block name="content"}
<!-- 查看物流页面 -->
<section class="track">
    <section class="track-con">
        <div class="order-track border_bottom">
            <div class="order-track-l">
                <img src="{$product_img}" alt="产品图"/>
            </div>
            <div class="order-track-r">
                <span class="track-status">物流状态：<em>{if $express_flow.status eq 200}{$express_state[{$express_flow.state}]}{else}暂无信息{/if}</em></span>
                <span>承运公司：{$order.delivery_name}</span>
                <span>运单编号：{$order.delivery_sn}</span>
            </div>
        </div>
        <div class="track-detail">
            {if $express_flow.status eq 200}
            <div class="track-detail-con">
                <i class="icon">&#xe60c;</i>
                <ul>
                    {foreach from=$express_flow.data item=data name=express_flow}
                    {if $smarty.foreach.express_flow.first}
                    <li class="selected">
                    {else}
                    <li>
                    {/if}
                        <span class="icon">&#xe611;</span>
                        <span>{$data.context}</span>
                        <p>{$data.time}</p>
                    </li>
                    {/foreach}
                </ul>
            </div>
            {else}
            <div class="track-detail-con">
                <i class="icon">&#xe61a;</i>
                <ul>
                    <li class="selected">
                        <span class="icon">&#xe636;</span>
                        <span>物流单暂无结果</span>
                        <p>{date('Y-m-d H:i:s')}</p>
                    </li>
                </ul>
            </div>
            {/if}
        </div>
    </section>
</section>
{/block}
{block name="footer"}
{/block}