{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>编辑资料</em></h1>
</header>
{/block}
{block name="content"}
<!-- 编辑资料 -->
<section class="userinfo">
    <div class="edit-userinfo">
        <label><span>会员卡号:</span><i class="red-font">{$user.account}</i></label>
        <label><span>会员等级:</span><i class="red-font">{$level[{$user.level_id}]}</i></label>
        <label><span>微信昵称:</span><i class="red-font">{$user.wx_nickname}</i></label>
        <label><span>真实姓名:</span>
            <input name="name" id="name" type="text" value="{$user.name}" placeholder="请输入真实姓名"/>
        </label>
        <label><span>手机号码:</span>
            <input name="mobile" id="mobile" type="tel" value="{$user.mobile}" placeholder="请输入手机号码" onblur="verify_mobile();"/>
        </label>
        <label for="sex"><span>性别:</span>
            <select id="sex" name="sex">
                <option value="N" {if $user.sex eq "N"}selected="selected"{/if}>保密</option>
                <option value="M" {if $user.sex eq "M"}selected="selected"{/if}>男</option>
                <option value="F" {if $user.sex eq "F"}selected="selected"{/if}>女</option>
            </select>
        </label>
        <label><span>邮箱:</span><input name="email" id="email" type="email" value="{$user.email}" placeholder="请输入邮箱"></label>
        <div class="info-btn">
            <a class="btn" href="javascript:;" onclick="edit_profile();">确认修改</a>
        </div>
    </div>
</section>
<div style="height: 2.2rem;"></div>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    var mobile = "{$user.mobile}";

    function verify_mobile() {
        var mobile = $("#mobile").val();

        if(mobile == "") {
            show_message_dialog("请输入手机号码");
            return false;
        }

        var url = "data_center.php";
        var data = { "opera":"verify_mobile", "mobile":mobile, "mode":"unique" };

        show_mask();
        $.post(url, data, verify_mobile_handler, "json");
    }

    function verify_mobile_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#mobile-show").text(response.mobile_mask);
            mobile = response.mobile;
        } else {
            show_message_dialog(response.msg);
            mobile = "";
        }
    }

    function edit_profile() {
        var sex = $("#sex").val();
        var email = $("#email").val();
        var name = $("#name").val();

        var msg = "";

        if(name == "") {
            msg += "-请填写真实姓名<br/>";
        }


        if(mobile == "") {
            msg += "-请填写有效的手机号码<br/>";
        }

        if(sex == "") {
            msg += "-请选择性别<br/>";
        }

        if(email == "") {
            msg += "-请填写邮箱<br/>";
        }

        if(msg != "") {
            show_message_dialog(msg);
        } else {
            var url = "profile.php";
            var data = { "opera":"edit", "email":email, "sex":sex, "mobile":mobile, "name":name };

            show_mask();
            $.post(url, data, edit_profile_handler, "json");
        }
    }

    function edit_profile_handler(response) {
        hide_mask();
        show_message_dialog(response.msg);
        if(response.error == 0) {
            $("#dialig_close_btn").click(function(){
                close_message_dialog();
                show_mask();
                window.location.reload();
            });

            $("#dialig_close").click(function(){
                close_message_dialog();
                show_mask();
                window.location.reload();
            });
        }
    }
</script>
{/block}