{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我的资产</em></h1>
</header>
{/block}
{block name="content"}
<!-- 我的资产 -->
<section class="wallet">
    <!-- 资产列表 -->
    <section class="f-section">
        <a class="slide-link" href="balance.php">
            <span class="icon" style="background-color: #ff0000;">&#xe614;</span>我的余额<em>￥{$member_info.balance}</em>
        </a>
        <a class="slide-link" href="reward.php">
            <span class="icon" style="background-color: #f0c040;">&#xe626;</span>我的奖金<em>￥{$member_info.reward}</em>
        </a>
        <a class="slide-link" href="reward_await.php">
            <span class="icon" style="background-color: #d0c0a6;">&#xe60b;</span>待发奖金<em>￥{$member_info.reward_await}</em>
        </a>
        <a class="slide-link" href="integral.php">
            <span class="icon" style="background-color: #fb9065;">&#xe616;</span>我的积分<em>{$member_info.integral}</em>
        </a>
    </section>
</section>
<div style="height: 2.2rem;"></div>
{/block}

{block name="footer"}
<section class="menu">
    <ul>
        <li><a href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="article_list.php"><em class="icon">&#xe603;</em><span>资讯</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="user.php"><em class="icon">&#xe600;</em><span>我</span></a></li>
    </ul>
</section>
{/block}