{extends file="index.phtml"}
{block name="header"}
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我要提现</em></h1>
    <a href="withdraw.php?act=list" class="edit">查看</a>
</header>
{/block}
{block name="content"}
<!-- 我要提现 -->
<section class="withdrawals">
    <div class="withdrawals-con">
        <label><span>可提现额:</span><i class="red_money">￥{sprintf("%.2f", $withdraw_await)}</i></label>
        <label><span>提现金额:</span><input type="tel" id="amount" name="amount" value="" placeholder="请输入提现金额"/></label>
        <label><span>手续费:</span><i class="red_money" id="fee">￥0.00</i></label>
        {foreach from=$bank_list item=bank name=bank_list}
        <label>
            <span>{if $smarty.foreach.bank_list.first}选择银行卡:{else}&nbsp;{/if}</span>
            <a href="javascript:select_bank_card({$bank.id});" id="bank_{$bank.id}" class="s-bank {if $smarty.foreach.bank_list.first}current{/if}">
                <i></i>{$bank.show_name}
            </a>
            <input type="hidden" name="bank_id" value="{$bank_list.0.id}" id="bank_id"/>
        </label>
        {/foreach}
        <label><span>&nbsp;</span><a href="bank.php?act=add" class="a-bank"><i>+</i>添加银行卡</a></label>
        <label><span>账户密码:</span><input id="password" type="password" name="账户密码" value="" placeholder="请输入账户密码"></label>
        <div class="withdrawals-btn">
            <a class="btn" href="javascript:void(0);" id="submit_withdraw_btn">确认提交</a>
        </div>
    </div>
</section>
<div style="height: 2.2rem;"></div>

<script type="text/javascript">
    var withdraw_await = {$withdraw_await};
    var fee_rate = {$config.fee_rate};
    var withdraw_min = {$config.withdraw_min};

    function select_bank_card(id) {
        $(".current").removeClass("current");

        $("#bank_"+id).addClass("current");
    }

    function submit_withdraw() {
        if(check_amount()) {
            var amount = $("#amount").val();
            var bank_id = $("#bank_id").val();
            var password = $("#password").val();
            var msg = "";

            amount = parseFloat(amount);
            bank_id = parseInt(bank_id);

            if(isNaN(amount) || amount <= 0) {
                amount = 0;
                $("#amount").val(amount.toFixed(2));
                $("#fee").text("￥0.00");
                msg += "-请填写要提现的金额<br/>";
            }

            if(isNaN(bank_id) || bank_id <= 0) {
                msg += "-请选择银行卡<br/>";
            }

            if(password == "") {
                msg += "-请填写账户密码<br/>";
            }

            if(msg == "") {
                var url = "withdraw.php";
                var data = { "opera":"add", "bank_id":bank_id, "password":password, "amount":amount };

                show_mask();
                $.post(url, data, submit_withdraw_handler, "json");
            } else {
                show_message_dialog(msg);
            }
        }
    }

    function submit_withdraw_handler(response) {
        hide_mask();
        show_message_dialog(response.msg);
        if(response.error == 0) {
            $("#dialog_close_btn").attr("href", "javascript:void(0);");
            $("#dialog_close_btn").click(function() {
                window.location.reload();
            });
            $("#dialog_close").click(function() {
                window.location.reload();
            });
        }
    }

    function check_amount() {
        var amount = $("#amount").val();
        amount = parseFloat(amount);

        if(isNaN(amount) || amount < 0) {
            amount = 0;
            $("#amount").val(amount.toFixed(2));
            $("#fee").text("￥0.00");
            return false;
        }

        if(amount < withdraw_min) {
            show_message_dialog("最小提现金额为:"+withdraw_min);
            return false;
        }

        var fee = fee_rate * amount;

        var total_amount = fee + amount;

        if(total_amount > withdraw_await) {
            show_message_dialog("可提现额不足");
            disable_btn("submit_withdraw_btn");
            $("#fee").text("￥" + fee.toFixed(2));
            return false;
        } else {
            enable_btn("submit_withdraw_btn");
        }

        $("#fee").text("￥" + fee.toFixed(2));
        return true;
    }

    $(function(){
        $("#amount").blur(function() { check_amount(); });

        $("#submit_withdraw_btn").click(function() { submit_withdraw(); });
        {if !$bank_list}
        show_message_dialog("请先添加银行卡");
        $("#dialog_close_btn").attr("href", "javascript:void(0);");
        $("#dialog_close_btn").click(function() {
            window.location.href = "bank.php?act=add";
        });
        $("#dialog_close").click(function() {
            window.history.back();
        });
        {/if}

    });

    function enable_btn(id) {
        $("#"+id).removeClass("btn-disabled");
    }

    function disable_btn(id) {
        $("#"+id).addClass("btn-disabled");
    }
</script>
{/block}
{block name="footer"}
{/block}