<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我要提现</em></h1>
</header>
<!-- 我要提现 -->
<section class="withdrawals">
    <div class="withdrawals-con">
        <label><span>可提现额:</span><i class="red_money">￥{sprintf("%.2f", $withdraw_await)}</i></label>
        <label><span>提现金额:</span><input type="tel" id="amount" name="amount" value="" placeholder="请输入提现金额"/></label>
        <label><span>手续费:</span><i class="red_money" id="fee">￥0.00</i></label>
        {foreach from=$bank_list item=bank name=bank_list}
        <label>
            <span>{if $smarty.foreach.bank_list.first}选择银行卡:{else}&nbsp;{/if}</span>
            <a href="javascript:select_bank_card({$bank.id});" id="bank_{$bank.id}" class="s-bank {if $smarty.foreach.bank_list.first}current{/if}">
                <i></i>{$bank.show_name}
            </a>
            <input type="hidden" name="bank_id" value="{$bank_list.0.id}" id="bank_id"/>
        </label>
        {/foreach}
        <label><span>&nbsp;</span><a href="bank.php?act=add" class="a-bank"><i>+</i>添加银行卡</a></label>
        <label><span>账户密码:</span><input id="password" type="password" name="账户密码" value="" placeholder="请输入账户密码"></label>
        <div class="withdrawals-btn">
            <a class="btn" href="javascript:void(0);" id="submit_withdraw_btn">确认提交</a>
        </div>
    </div>
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.php"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="user.php"><em class="icon">&#xe604;</em><span>我</span></a></li>
    </ul>
</section>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();" id="dialog_close_btn">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace" id="dialog_close">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    var withdraw_await = {$withdraw_await};
    var fee_rate = {$config.fee_rate};
    var withdraw_min = {$config.withdraw_min};

    function select_bank_card(id) {
        $(".current").removeClass("current");

        $("#bank_"+id).addClass("current");
    }

    function submit_withdraw() {
        if(check_amount()) {
            var amount = $("#amount").val();
            var bank_id = $("#bank_id").val();
            var password = $("#password").val();
            var msg = "";

            amount = parseFloat(amount);
            bank_id = parseInt(bank_id);

            if(isNaN(amount) || amount <= 0) {
                amount = 0;
                $("#amount").val(amount.toFixed(2));
                $("#fee").text("￥0.00");
                msg += "-请填写要提现的金额<br/>";
            }

            if(isNaN(bank_id) || bank_id <= 0) {
                msg += "-请选择银行卡<br/>";
            }

            if(password == "") {
                msg += "-请填写账户密码<br/>";
            }

            if(msg == "") {
                var url = "withdraw.php";
                var data = { "opera":"add", "bank_id":bank_id, "password":password, "amount":amount };

                show_mask();
                $.post(url, data, submit_withdraw_handler, "json");
            } else {
                show_message_dialog(msg);
            }
        }
    }

    function submit_withdraw_handler(response) {
        hide_mask();
        show_message_dialog(response.msg);
        if(response.error == 0) {
            $("#dialog_close_btn").attr("href", "javascript:void(0);");
            $("#dialog_close_btn").click(function() {
                window.location.reload();
            });
            $("#dialog_close").click(function() {
                window.location.reload();
            });
        }
    }

    function check_amount() {
        var amount = $("#amount").val();
        amount = parseFloat(amount);

        if(isNaN(amount) || amount < 0) {
            amount = 0;
            $("#amount").val(amount.toFixed(2));
            $("#fee").text("￥0.00");
            return false;
        }

        if(amount < withdraw_min) {
            show_message_dialog("最小提现金额为:"+withdraw_min);
            return false;
        }

        var fee = fee_rate * amount;

        var total_amount = fee + amount;

        if(total_amount > withdraw_await) {
            show_message_dialog("可提现额不足");
            disable_btn("submit_withdraw_btn");
            $("#fee").text("￥" + fee.toFixed(2));
            return false;
        } else {
            enable_btn("submit_withdraw_btn");
        }

        $("#fee").text("￥" + fee.toFixed(2));
        return true;
    }

    $(function(){
        $("#amount").blur(function() { check_amount(); });

        $("#submit_withdraw_btn").click(function() { submit_withdraw(); });
        {if !$bank_list}
            show_message_dialog("请先添加银行卡");
            $("#dialog_close_btn").attr("href", "javascript:void(0);");
            $("#dialog_close_btn").click(function() {
                window.location.href = "bank.php?act=add";
            });
            $("#dialog_close").click(function() {
                window.location.href = "bank.php?act=add";
            });
        {/if}

        {if $no_privicy}
            show_message_dialog("请先升级为合伙人");
            $("#dialog_close_btn").attr("href", "javascript:void(0);");
            $("#dialog_close_btn").click(function() {
                window.location.href = "copartner.php";
            });
            $("#dialog_close").click(function() {
                window.location.href = "copartner.php";
            });
        {/if}
    });

            function show_message_dialog(message) {
                $(".cd-popup").addClass("is-visible");
                $(".progressbar").hide();
                $("#dialog-message").html(message);
                $("#message_dialog").show();
            }

            function close_message_dialog() {
                $(".cd-popup").removeClass("is-visible");
                $("#message_dialog").hide();
            }

            function show_mask() {
                $(".cd-popup").addClass("is-visible");
                $(".progressbar").show();
            }

            function hide_mask() {
                $(".cd-popup").removeClass("is-visible");
                $(".progressbar").hide();
            }

            function enable_btn(id) {
                $("#"+id).removeClass("btn-disabled");
            }

            function disable_btn(id) {
                $("#"+id).addClass("btn-disabled");
            }
</script>
</body>
</html>
