{include file="library/header.lbi"}
<body xmlns="http://www.w3.org/1999/html">
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}

<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        {if $act eq 'view'}
        <div class="pull-right"><a class="btn btn-primary" href="?act=add">新增产品</a></div>
        {/if}
        <div class="clear"></div>
    </div>
    <div class="adminGroup-main">
        {if $act eq 'view'}
        <div class="article-main-header">
            <form action="" method="get" />
            <fieldset>
                <p>
                <div class="pull-left">
                    显示
                    <select name="count" class="w75">
                        <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                        <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                        <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                        <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                    </select>
                    项结果
                </div>
                <div class="pull-right">
                    <label>产品编号：</label>
                    <input class="text-input w150" type="text" id="small-input" name="product_sn" value="{$product_sn}">&nbsp;
                    <label>状态：</label>
                    <select name="status">
                        <option value="-1">全部</option>
                        <option value="0" {if $status eq 0}selected="selected"{/if}>下架</option>
                        <option value="1" {if $status eq 1}selected="selected"{/if}>上架</option>
                    </select>&nbsp;
                    <button type="submit" class="btn btn-default">搜索</button>
                </div>
                </p>
            </fieldset>
            </form>
            <div class="clear"></div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>产品编号</th>
                <th>产品名称</th>
                <th>价格</th>
                <!--
                <th>购买积分</th>
                <th>赠送积分</th>
                -->
                <th>产品分类</th>
                <th>库存</th>
                <th>状态</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$product_list item=product}
            <tr>
                <td>{$product.product_sn}</td>
                <td>{$product.name}</td>
                <td>{$product.price}</td>
                <!--
                <td>{$product.integral}</td>
                <td>{$product.integral_given}</td>
                -->
                <td>{$cat_json[$product.category_id]}</td>
                <td>{$product.inventory}</td>
                <td>{$LANG.product["status_{$product.status}"]}</td>
                <td>
                    {$product.operation}
                </td>
            </tr>
            {/foreach}
            <tr>
                <td colspan="9">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&keyword={$keyword}&count={$count}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&keyword={$keyword}&count={$count}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&keyword={$keyword}&count={$count}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&keyword={$keyword}&count={$count}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&keyword={$keyword}&count={$count}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
        {/if}

        <!-- 产品编辑 -->
        {if $act eq 'edit' or $act eq 'add'}
        <script type="text/javascript" src="../plugins/kindeditor/kindeditor-all-min.js"></script>
        <form method="post" name="product">
            <fieldset>
                {if $act eq 'edit'}
                <p>
                    <label class="l-title">产品编号：</label>
                    {$product.product_sn}
                </p>
                {/if}
                <p class="clear">
                    <label class="l-title">产品分类：</label>
                    <select name="category_id" id="category_id" class="w150">
                        {foreach from=$category_list item=cat}
                        <option value="{$cat.id}">{$cat.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p>
                    <label class="l-title">产品名称：</label>
                    <input class="text-input w300" type="text" id="name" name="name" placeholder="请输入产品名称" value="{if $act eq 'edit'}{$product.name}{/if}">
                </p>

                <p>
                    <label class="l-title">产品价格：</label>
                    <input class="text-input w300" type="text" id="price" name="price" placeholder="请输入产品价格" value="{if $act eq 'edit'}{$product.price}{/if}">
                </p>

                <p style="display: none;">
                    <label class="l-title">产品积分：</label>
                    <input class="text-input w300" type="text" id="integral" name="integral" placeholder="请输入购买积分" value="{if $act eq 'edit'}{$product.integral}{/if}0">
                </p>

                <p style="display: none;">
                    <label class="l-title">赠送积分：</label>
                    <input class="text-input w300" type="text" id="price_integral" name="integral_given" placeholder="请输入赠送积分" value="{if $act eq 'edit'}{$product.integral_given}{/if}0">
                </p>

                <p>
                    <label class="l-title">产品库存：</label>
                    <input class="text-input w300" type="text" id="inventory" name="inventory" placeholder="请输入库存" value="{if $act eq 'edit'}{$product.inventory}{/if}">
                </p>
                <p class="clear">
                    <label class="l-title">产品状态：</label>
                    <select name="status" id="status" class="w150">
                        <option value="1">上架</option>
                        <option value="0">下架</option>
                    </select>
                </p>
                <p class="clear" id="img-input">
                    <label class="l-title">产品图片:</label>
                    <input type="button" class="text-input" id="select-image" value="请选择产品图片" style="cursor:pointer">
                    <input type="hidden" name="img" value="" id="img"/>
                </p>
                <p>
                    <label class="l-title"></label>
                    <img id="show-image" alt="" src="{if $act eq 'edit'}{$product.img}{else}about:blank{/if}">
                </p>
                <h5>产品详情：</h5>
                <p>
                    <textarea name="desc" id="desc" class="rn w-90" rows="20" placeholder="这里是编辑器">{if $act eq 'edit'}{$product.desc}{/if}</textarea>
                </p>
                <p>
                    <label class="l-title"></label>
                    {if $act eq 'edit'}
                    <input type="hidden" name="opera" value="edit"/>
                    <input type="hidden" name="eproduct_sn" value="{$product.product_sn}">
                    {/if}

                    {if $act eq 'add'}
                    <input type="hidden" name="opera" value="add"/>
                    {/if}

                    <button class="btn btn-primary" type="submit">{if $act eq 'edit'}修改{else}新增{/if}</button> &nbsp;<a href="product.php" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
        <script type="text/javascript">
            $(function() {
                {if $act eq 'edit'}
                $("#category_id").val({$product.category_id});
                $("#status").val({$product.status});
                {/if}
            });

            KindEditor.ready(function(K) {
                var editor1 = K.create("textarea[name='desc']", {
                    height: '400px',
                    width: '93%',
                    cssPath: '../plugins/kindeditor/plugins/code/prettify.css',
                    uploadJson: '../plugins/kindeditor/upload_json.php',
                    fileManagerJson: '../plugins/kindeditor/file_manager_json.php',
                    allowFileManager: true,
                    afterCreate: function () {
                        var self = this;
                        K.ctrl(document, 13, function () {
                            self.sync();
                            K('form[name=product]')[0].submit();
                        });
                        K.ctrl(self.edit.doc, 13, function () {
                            self.sync();
                            K('form[name=product]')[0].submit();
                        });
                    }
                });

                var editor = K.editor({
                    allowFileManager : true,
                    uploadJson : '../plugins/kindeditor/section_upload_json.php',
                    fileManagerJson : '../plugins/kindeditor/file_manager_json.php'
                });

                K('#select-image').click(function() {
                    editor.loadPlugin('image', function() {
                        editor.plugin.imageDialog({
                            imageUrl : '',
                            clickFn : function(url, title, width, height, border, align) {
                                if( !width ) {
                                    width = '300';
                                    width = (width == '') ? '75px' : width + 'px'
                                }
                                if( !height ) {
                                    height = '300';
                                    height = (height == '') ? '75px' : height + 'px'
                                }

                                K('#img').val(url);
//                        K('#select-image').val('');
                                K('#show-image').attr('src', url);
                                K('#show-image').css('width', width);
                                K('#show-image').css('height', height);
                                K('#show-image').css('display', 'block');
//                        K('#show-image').css('display', 'block');
                                editor.hideDialog();
                            }
                        });
                    });
                });
            });
        </script>
        {/if}
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>