{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}

<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="adminGroup-main">
        {if $act eq 'view'}
        <div class="article-main-header">
            <form action="" method="get" />
            <fieldset>
                <p>
                <div class="pull-left">
                    显示
                    <select name="count" class="w75">
                        <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                        <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                        <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                        <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                    </select>
                    项结果
                </div>
                <div class="pull-right">
                    <label>会员编号：</label>
                    <input class="text-input w150" type="text" id="small-input" name="account" value="{$account}">&nbsp;
                    <label>明细类型：</label>
                    <select name="type">
                        <option value="0">全部</option>
                        {foreach from=$lang.account_type key=id item=type_item}
                        <option value="{$id}" {if $type eq $id}selected="selected"{/if}>{$type_item}</option>
                        {/foreach}
                    </select>&nbsp;<br/><br/>
                    <label>起止时间：</label>
                    <input class="text-input w150" type="text" id="begin_time" name="begin_time" value="{$begin_time}">&nbsp;
                     至
                    <input class="text-input w150" type="text" id="end_time" name="end_time" value="{$end_time}">&nbsp;
                    <button type="submit" class="btn btn-default">搜索</button>
                </div>
                </p>
            </fieldset>
            </form>
            <div class="clear"></div>
            <fieldset>
                <div class="pull-left">
                    <a class="btn btn-primary" href="javascript:order_export();">导出全部记录</a>
                    <a class="btn btn-primary" href="javascript:order_selected_export();">导出选中记录</a>
                </div>
                <div class="clear"></div>
            </fieldset>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th><a href="javascript:select_all();">全选</a>/<a href="javascript:deselect();">反选</a></th>
                <th>记录ID</th>
                <th>会员账号</th>
                <th>奖金余额</th>
                <th>待发奖金</th>
                <th>账户余额</th>
                <th>操作时间</th>
                <th>交易类型</th>
                <th>备注</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$account_list item=a}
            <tr>
                <td><input type="checkbox" name="id[]" value="{$a.id}"/></td>
                <td>{$a.id}</td>
                <td>{$a.account}</td>
                <td>{if $a.reward gt 0}+{/if}{$a.reward}</td>
                <td>{if $a.reward_await gt 0}+{/if}{$a.reward_await}</td>
                <td>{if $a.balance gt 0}+{/if}{$a.balance}</td>
                <td>{date('Y-m-d H:i:s', $a.add_time)}</td>
                <td>{$lang.account_type["{$a.type}"]}</td>
                <td>{$a.remark}</td>
            </tr>
            {/foreach}
            <tr>
                <td colspan="9">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&account={$account}&type={$type}&begin_time={$begin_time}&end_time={$end_time}&count={$count}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&account={$account}&type={$type}&begin_time={$begin_time}&end_time={$end_time}&count={$count}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&account={$account}&type={$type}&begin_time={$begin_time}&end_time={$end_time}&count={$count}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&account={$account}&type={$type}&begin_time={$begin_time}&end_time={$end_time}&count={$count}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&account={$account}&type={$type}&begin_time={$begin_time}&end_time={$end_time}&count={$count}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
        <script type="text/javascript" src="laydate/laydate.js"></script>
        <script type="text/javascript">
            var start = {
                elem: '#begin_time',
                format: 'YYYY-MM-DD',
                max: '9999-12-31 23:59:59', //最大日期
                istime: false,
                istoday: true,
                choose: function(datas){
                    end.min = datas; //开始日选好后，重置结束日的最小日期
                    end.start = datas //将结束日的初始值设定为开始日
                    end.click;
                }
            };

            var end = {
                elem: '#end_time',
                format: 'YYYY-MM-DD',
                max: '9999-12-31 23:59:59',
                istime: false,
                istoday: true,
                choose: function(datas){
                    start.max = datas; //结束日选好后，重置开始日的最大日期
                }
            };

            laydate.render(start);
            laydate.render(end);
        </script>
        <script type="text/javascript">
            function order_export() {
                var form = $("<form>");
                form.attr({
                    "style":"display:none;",
                    "method": "post",
                    "action": window.location.href
                });

                var input = $("<input>");
                input.attr({
                    "type": "hidden",
                    "name": "opera",
                    "value": "export"
                });

                form.append(input);
                $("html").append(form);
                form.submit();
            }

            function order_selected_export() {
                var order_id = "";

                $("input[name='id[]']").each(function(i, e){
                    if(e.checked) {
                        order_id += e.value+",";
                    }
                });

                if(order_id == "") return false;

                var form = $("<form>");
                form.attr({
                    "style":"display:none;",
                    "method": "post",
                    "action": window.location.href
                });

                var input = $("<input>");
                input.attr({
                    "type": "hidden",
                    "name": "opera",
                    "value": "export"
                });

                form.append(input);

                var input = $("<input>");
                input.attr({
                    "type": "hidden",
                    "name": "account_id",
                    "value": order_id
                });

                form.append(input);

                $("html").append(form);
                form.submit();
            }

            function select_all() {
                $("input[name='id[]']").each(function(i, e){
                    e.checked = true;
                });
            }

            function deselect() {
                $("input[name='id[]']").each(function(i, e){
                    if(e.checked) {
                        e.checked = false;
                    } else {
                        e.checked = true;
                    }
                });
            }
        </script>
        {/if}
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>