{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$delivery.name}--配送区域</h5>
        <div class="pull-right"><a class="btn btn-primary" href="javascript:history.go(-1);">返回</a>&nbsp;</div>
        <div class="pull-right"><a class="btn btn-primary" href="express.php?act=delivery_area_set&delivery_id={$delivery.id}">新增配送区域</a>&nbsp;</div>
        <div class="clear"></div>
    </div>
    <div class="article-main-header">
        <div class="clear"></div>
    </div>
    <div class="article-main">
        <table class="table">
            <thead>
            <tr>
                <th>区域名称</th>
                <th>首重费用</th>
                <th>续重费用</th>
                <th>减免费用</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$area_list item=area}
            <tr>
                <td>{$area.name}</td>
                <td>{$area.first_weight}</td>
                <td>{$area.next_weight}</td>
                <td>{$area.free}</td>
                <td>
                    <a href="express.php?act=delivery_area_edit&id={$area.id}">编辑</a> |
                    <a href="javascript:if(confirm('您确定要删除该区域？')) window.location.href = 'express.php?act=delivery_area_delete&id={$area.id}';">删除</a>
                </td>
            </tr>
            {/foreach}
            </tbody>
        </table>
    </div>
</div>
<!-- END content -->
{include file="library/footer.lbi"}
</body>
</html>