{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}

<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="adminGroup-main">
        {if $act eq 'view'}
        <div class="article-main-header">
            <form action="" method="get" />
            <fieldset>
                <p>
                <div class="pull-left">
                    显示
                    <select name="count" class="w75">
                        <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                        <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                        <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                        <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                    </select>
                    项结果
                </div>
                <div class="pull-right">
                    <label>会员编号：</label>
                    <input class="text-input w150" type="text" id="small-input" name="account" value="{$account}">&nbsp;
                    <button type="submit" class="btn btn-default">搜索</button>
                </div>
                </p>
            </fieldset>
            </form>
            <div class="clear"></div>
            <fieldset>
                <div class="pull-left">
                    <a class="btn btn-primary" href="?act=network">查看网络图</a>
                </div>
                <div class="clear"></div>
            </fieldset>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>会员账号</th>
                <th>会员等级</th>
                <th>真实姓名</th>
                <th>账户余额</th>
                <th>奖金余额</th>
                <th>待发奖金</th>
                <th>注册时间</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$member_list item=member}
            <tr>
                <td>{$member.account}</td>
                <td>{$lang.level[{$member.level_id}]}</td>
                <td>{$member.name}</td>
                <td>{$member.balance}</td>
                <td>{$member.reward}</td>
                <td>{$member.reward_await}</td>
                <td>{date('Y-m-d H:i:s', $member.add_time)}</td>
                <td>
                    {$member.operation}
                </td>
            </tr>
            {/foreach}
            <tr>
                <td colspan="8">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&keyword={$keyword}&count={$count}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&keyword={$keyword}&count={$count}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&keyword={$keyword}&count={$count}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&keyword={$keyword}&count={$count}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&keyword={$keyword}&count={$count}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
        <script type="text/javascript">
            function open_network(account) {
                if(account == '') {
                    return false;
                }

                if(confirm("您确定要允许该会员查看网络图？")) {
                    $.post('member.php', { "opera":"open_network", "account":account }, ajax_handler, "json");
                    return true;
                }
                return false;
            }

            function close_network(account) {
                if(account == '') {
                    return false;
                }

                if(confirm("您确定要禁止该会员查看网络图？")) {
                    $.post('member.php', { "opera":"close_network", "account":account }, ajax_handler, "json");
                    return true;
                }
                return false;
            }

            function frozen(account) {
                if(account == '') {
                    return false;
                }

                if(confirm("您确定要冻结该会员？")) {
                    $.post('member.php', { "opera":"frozen", "account":account }, ajax_handler, "json");
                    return true;
                }
                return false;
            }

            function release(account) {
                if(account == '') {
                    return false;
                }

                if(confirm("您确定要解冻该会员？")) {
                    $.post('member.php', { "opera":"release", "account":account }, ajax_handler, "json");
                    return true;
                }
                return false;
            }

            function unlock(account) {
                if(account == '') {
                    return false;
                }

                if(confirm("您确定要解锁该会员？")) {
                    $.post('member.php', { "opera":"unlock", "account":account }, ajax_handler, "json");
                    return true;
                }
                return false;
            }
            //锁定用户
            function lock(account) {
                if(account == '') {
                    return false;
                }

                if(confirm("您确定要锁定该会员？")) {
                    $.post('member.php', { "opera":"lock", "account":account }, ajax_handler, "json");
                    return true;
                }
                return false;
            }

            function ajax_handler(response) {
                alert(response.msg);
                window.location.reload();
            }
            //重置密码
            function reset_password(account) {
                if(account == '') {
                    return false;
                }

                if(confirm("您确定要重置该会员的密码？")) {
                    $.post('member.php', { "opera":"reset", "account":account }, reset_password_handler, "json");
                    return true;
                }
                return false;
            }

            function reset_password_handler(response) {
                alert(response.msg);
            }
        </script>
        {/if}

        {if $act eq 'network'}
        <fieldset>
            <div class="pull-left">
                <a class="btn btn-primary" href="javascript:history.back();">返回</a>
            </div>
            <div class="clear"></div>
        </fieldset>
        <div id="ztree" class="ztree"></div>
        <link type="text/css" rel="stylesheet" href="css/zTreeStyle.css"/>
        <script type="text/javascript" src="js/jquery.ztree.core-3.5.min.js"></script>
        <script type="text/javascript">
            var setting = {
                async: {
                    enable: true,
                    url: "member.php?act=get_node",
                    autoParam: ["id"]
                }
            };

            $(function(){
                var t = $("#ztree");
                t = $.fn.zTree.init(t, setting);
            });
        </script>
        {/if}

        <!-- 会员充值 -->
        {if $act eq 'recharge'}
        <form method="post">
            <fieldset>
                <p>
                    <label class="l-title">会员账号：</label>
                    {$member_info.account}
                </p>
                <p>
                    <label class="l-title">真实姓名：</label>
                    {$member_info.name}
                </p>
                <p>
                    <label class="l-title">账户余额：</label>
                    {$member_info.emoney}
                </p>
                <p>
                    <label class="l-title">充值金额：</label>
                    <input class="text-input w300" type="text" id="emoney" name="emoney" placeholder="请输入充值金额" value="">
                </p>
                <p>
                    <label class="l-title">备注：</label>
                    <input class="text-input w300" type="text" id="remark" name="remark" placeholder="请输入备注" value="">
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="recharge"/>
                    <input type="hidden" name="eaccount" value="{$member_info.account}">
                    <button class="btn btn-primary" type="submit">提交</button> &nbsp;<a href="member.php" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
        {/if}

        {if $act eq 'edit'}
        <form method="post">
            <fieldset>
                <p>
                    <label class="l-title">会员账号：</label>
                    {$member_info.account}
                </p>
                <p>
                    <label class="l-title">真实姓名：</label>
                    <input type="text" name="name" value="{$member_info.name}"/>
                </p>
                <p>
                    <label class="l-title">会员等级：</label>
                    <select name="level_id">
                        {foreach from=$member_level item=level key=id}
                        {if $id >= $member_info.level_id}
                        <option value="{$id}" {if $id eq $member_info.level_id}selected="selected"{/if}>{$level}</option>
                        {/if}
                        {/foreach}
                    </select>
                </p>
                <p>
                    <label class="l-title">手机号码：</label>
                    <input class="text-input w300" type="text" id="mobile" name="mobile" placeholder="" value="{$member_info.mobile}">
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="edit"/>
                    <input type="hidden" name="eaccount" value="{$member_info.account}">
                    <button class="btn btn-primary" type="submit">提交</button> &nbsp;<a href="member.php" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
        {/if}
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>