{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$payment_plugins.name}参数设置</h5>
        <div class="clear"></div>
    </div>
    <div class="nav-main">
        <form id="navForm" name="navAddForm" method="post">
            <fieldset>
                {foreach from=$payment_plugins.configures item=configure}
                <p>
                    <label class="l-title">{$configure.name}：</label>
                    <input class="text-input w300" type="text" value="{if isset($payment_plugins.configure[{$configure.key}])}{$payment_plugins.configure[{$configure.key}]}{/if}" id="{$configure.key}" name="configure[{$configure.key}]" placeholder="请输入{$configure.name}"/>
                </p>
                {foreachelse}
                该插件不需要配置参数
                {/foreach}
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="eid" value="{$payment_plugins.id}"/>
                    <input type="hidden" name="opera" value="edit"/>
                    <button class="btn btn-primary" type="submit">设置</button> &nbsp;<a href="payment.php" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
    </div>
</div>
{include file="library/footer.lbi"}
</body>
</html>