{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}

<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="adminGroup-main">
        {if $act eq 'view'}
        <div class="article-main-header">
            <form action="" method="get" />
            <fieldset>
                <p>
                <div class="pull-left">
                    显示
                    <select name="count" class="w75">
                        <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                        <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                        <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                        <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                    </select>
                    项结果
                </div>
                <div class="pull-right">
                    <label>订单编号：</label>
                    <input class="text-input w150" type="text" id="small-input" name="order_sn" value="{$order_sn}">&nbsp;
                    <label>会员编号：</label>
                    <input class="text-input w150" type="text" id="small-input" name="account" value="{$account}">&nbsp;
                    <label>明细类型：</label>
                    <select name="status">
                        <option value="0">全部</option>
                        <option value="1" {if $status eq 1}selected="selected"{/if}>待发货</option>
                        <option value="2" {if $status eq 2}selected="selected"{/if}>已发货</option>
                    </select><br/><br/>
                    <label>起止时间：</label>
                    <input class="text-input w150" type="text" id="begin_time" name="begin_time" value="{$begin_time}">&nbsp;
                    至
                    <input class="text-input w150" type="text" id="end_time" name="end_time" value="{$end_time}">&nbsp;
                    <button type="submit" class="btn btn-default">搜索</button>
                </div>
                </p>
            </fieldset>
            </form>
            <div class="clear"></div>
            <fieldset>
                <div class="pull-left">
                    <a class="btn btn-primary" href="javascript:order_export();">导出全部订单</a>
                    <a class="btn btn-primary" href="javascript:order_selected_export();">导出选中订单</a>
                </div>
                <div class="clear"></div>
            </fieldset>
        </div>
        {/if}
        {if $act eq 'view'}
        <table class="table">
            <thead>
            <tr>
                <th><a href="javascript:select_all();">全选</a>/<a href="javascript:deselect();">反选</a></th>
                <th>订单编号</th>
                <th>会员账号</th>
                <th>订单总额</th>
<!--                <th>积分总额</th>-->
<!--                <th>赠送积分</th>-->
                <th>订单状态</th>
                <th>下单时间</th>
                <th>备注</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$order_list item=order}
            <tr>
                <td><input type="checkbox" name="id[]" value="{$order.id}"/></td>
                <td>{$order.order_sn}</td>
                <td>{$order.account}</td>
                <td>{$order.amount}</td>
<!--                <td>{$order.integral_amount}</td>-->
<!--                <td>{$order.integral_given_amount}</td>-->
                <td>{$LANG.order["status_{$order.status}"]}</td>
                <td>{date('Y-m-d H:i:s', $order.add_time)}</td>
                <td>{$order.remark}</td>
                <td>
                    {$order.operation}
                </td>
            </tr>
            {/foreach}
            <tr>
                <td colspan="10">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&status={$stauts}&account={$account}&count={$count}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&status={$stauts}&account={$account}&count={$count}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&status={$stauts}&account={$account}&count={$count}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&status={$stauts}&account={$account}&count={$count}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&status={$stauts}&account={$account}&count={$count}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
        <script type="text/javascript" src="laydate/laydate.js"></script>
        <script type="text/javascript">
            var start = {
                elem: '#begin_time',
                format: 'YYYY-MM-DD',
                max: '9999-12-31 23:59:59', //最大日期
                istime: false,
                istoday: true,
                choose: function(datas){
                    end.min = datas; //开始日选好后，重置结束日的最小日期
                    end.start = datas //将结束日的初始值设定为开始日
                    end.click;
                }
            };

            var end = {
                elem: '#end_time',
                format: 'YYYY-MM-DD',
                max: '9999-12-31 23:59:59',
                istime: false,
                istoday: true,
                choose: function(datas){
                    start.max = datas; //结束日选好后，重置开始日的最大日期
                }
            };

            laydate(start);
            laydate(end);
        </script>
        <script type="text/javascript">
            function order_export() {
                var form = $("<form>");
                form.attr({
                    "style":"display:none;",
                    "method": "post",
                    "action": window.location.href
                });

                var input = $("<input>");
                input.attr({
                    "type": "hidden",
                    "name": "opera",
                    "value": "export"
                });

                form.append(input);
                $("html").append(form);
                form.submit();
            }

            function order_selected_export() {
                var order_id = "";

                $("input[name='id[]']").each(function(i, e){
                    if(e.checked) {
                        order_id += e.value+",";
                    }
                });

                if(order_id == "") return false;

                var form = $("<form>");
                form.attr({
                    "style":"display:none;",
                    "method": "post",
                    "action": "order.php"
                });

                var input = $("<input>");
                input.attr({
                    "type": "hidden",
                    "name": "opera",
                    "value": "export"
                });

                form.append(input);

                var input = $("<input>");
                input.attr({
                    "type": "hidden",
                    "name": "order_id",
                    "value": order_id
                });

                form.append(input);

                $("html").append(form);
                form.submit();
            }

            function select_all() {
                $("input[name='id[]']").each(function(i, e){
                    e.checked = true;
                });
            }

            function deselect() {
                $("input[name='id[]']").each(function(i, e){
                    if(e.checked) {
                        e.checked = false;
                    } else {
                        e.checked = true;
                    }
                });
            }
        </script>
        {/if}

        <!-- 充值处理 -->
        {if $act eq 'edit' or $act eq 'detail'}
        <form method="post">
            <fieldset>
                <p>
                    <label class="l-title">订单编号：</label>
                    {$order.order_sn}
                </p>
                <p>
                    <label class="l-title">会员账号：</label>
                    {$order.account}
                </p>
                <p>
                    <label class="l-title">订单总额：</label>
                    {$order.amount}
                </p>
                <p>
                    <label class="l-title">积分总额：</label>
                    {$order.integral_amount}
                </p>
                <p>
                    <label class="l-title">赠送积分：</label>
                    {$order.integral_given_amount}
                </p>
                <p>
                    <label class="l-title">备注：</label>
                    {$order.remark}
                </p>
                <p>
                    <label class="l-title">收货信息：</label>
                    收货人：{$order.consignee}
                    联系电话：{$order.mobile}
                    收货地址：{$order.address}
                    邮政编码：{$order.zipcode}
                </p>
                {if $order.status eq 2 and $act eq 'detail'}
                <p>
                    <label class="l-title">物流信息：</label>
                    物流公司：{$order.delivery_company}
                    物流单号：{$order.delivery_sn}
                </p>
                {/if}
                <p>
                    <label class="l-title">订单详情:</label>
                    <table class="table">
                        <thead>
                        <tr><th>产品编号</th><th>产品名称</th><th>产品价格</th><th>积分</th><th>赠送积分</th><th>购买数量</th></tr>
                        </thead>
                        {foreach from=$order_detail item=product}
                        <tr>
                            <td>{$product.product_sn}</td>
                            <td>{$product.name}</td>
                            <td>{$product.price}</td>
                            <td>{$product.integral}</td>
                            <td>{$product.integral_given}</td>
                            <td>{$product.number}</td>
                        </tr>
                        {/foreach}
                    </table>
                </p>
                {if $act eq 'edit'}
                <p>
                    <label class="l-title">物流公司：</label>
                    <input class="text-input w300" type="text" id="delivery_company" name="delivery_company" placeholder="请输入物流公司" value="">
                </p>
                <p>
                    <label class="l-title">物流单号：</label>
                    <input class="text-input w300" type="text" id="delivery_sn" name="delivery_sn" placeholder="请输入物流单号" value="">
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="edit"/>
                    <input type="hidden" name="eorder_sn" value="{$order.order_sn}">
                    <button class="btn btn-primary" type="submit">设为已发货</button> &nbsp;<a href="order.php" class="btn btn-primary">返回</a>
                </p>
                {/if}
            </fieldset>
        </form>
        {/if}
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>