<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{$pageTitle}</title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <style type="text/css">
        <!--
        .print-table {
            text-align: center;
            line-height: 26px;
            font-size: 14px;
            background: #333;
        }
        .print-table-img {
            position: absolute;
            left: 0;
            top: 0;
            height: 40px;
        }
        .print-title {
            font-size: 20px;
            text-align: center;
            line-height: 40px;
            margin: 0;
            padding: 0;
            margin-bottom: 10px;
        }
        tr {
            background: #fff;
        }
        .print-btn {
            display: block;
            margin: 10px auto;
            width: 120px;
            line-height: 30px;
            text-align: center;
            background: rgb(44, 45, 115);
            text-decoration: none;
            color: #fff;
        }
        #print-area {
            position: relative;
        }
        .print-qrcode {
            position: absolute;
            right: 1px;
            bottom: 1px;
            height: 98px;
        }
        -->
    </style>
</head>
<body>
<!-- 打印发货单 -->
<div id="print-area">
<h1 class="print-title">
    <img src="images/tb_logo.jpg" class="print-table-img"/>
    发货单
</h1>
<table class="print-table" border="0" cellpadding="3" cellspacing="1" width="100%" align="center">
    <tr>
        <td colspan="3" align="left">客户收货地址：{$order.address}</td>
        <td colspan="2" align="left">邮编：{$order.zipcode}</td>
        <td colspan="2" align="left">电话：{$order.mobile}</td>
    </tr>
    <tr>
        <td colspan="3" align="left">收货人：{$order.consignee}</td>
        <td colspan="2" align="left">单号：{$order.order_sn}</td>
        <td colspan="2" align="left">日期：{date('Y-m-d', $order.add_time)}</td>
    </tr>
    <tr>
        <td>序号</td>
        <td>商品名称</td>
        <td>规格</td>
        <td>单位</td>
        <td>数量</td>
        <td>单价（元）</td>
        <td>金额（元）</td>
<!--        <td>PV值</td>-->
<!--        <td>PV值合计</td>-->
    </tr>
    {foreach from=$order_detail item=product name=order_detail}
    <tr>
        <td>{$smarty.foreach.order_detail.iteration}</td>
        <td>{$product.name}</td>
        <td></td>
        <td></td>
        <td>{$product.number}</td>
        <td>{$product.price}</td>
        <td>{sprintf('%.2f', $product.price*$product.number)}</td>
<!--        <td></td>-->
<!--        <td></td>-->
    </tr>
    {/foreach}
    <tr>
        <td colspan="4">合计</td>
        <td>{count($order_detail)}</td>
        <td></td>
        <td>{$order.amount}</td>
<!--        <td></td>-->
<!--        <td></td>-->
    </tr>
    <tr>
        <td colspan="7" align="left"><strong>合计</strong>（大写）：{$order.amount_upper}</td>
    </tr>
    <tr>
        <td colspan="7" align="left">备注：{$order.remark}</td>
    </tr>
    <tr>
        <td colspan="7" align="left">注：第一联：白色单 - 财务部 第二联：红色单 - 客户 第三联：蓝色单 - 物流部 第四联：黄色单 - 仓库</td>
    </tr>
    <tr align="left">
        <td colspan="1">发货人：杨宽</td>
        <td colspan="2">部门：物流部</td>
        <td colspan="2">公司电话：0398-2513666</td>
        <td colspan="2">公司传真：0398-2513669</td>
    </tr>
    <tr align="left">
        <td colspan="7">发货公司：三门峡九健电子商务有限公司</td>
    </tr>
    <tr align="left">
        <td colspan="7">地址：三门峡市湖滨区五原西路商会大厦A座17层 邮编：472000</td>
    </tr>
    <tr align="left">
        <td colspan="2">财务：</td>
        <td colspan="2">发货人：</td>
        <td colspan="2">制单人：</td>
        <td colspan="1"></td>
    </tr>
</table>
<img src="images/qrcode.jpg" class="print-qrcode"/>
</div>
<a href="javascript:void(0);" onclick="jsprint();" class="print-btn">打印发货单</a>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript">
    function jsprint() {
        $(".print-btn").hide();
        window.print();
        $(".print-btn").show();
    }
</script>
</body>
</html>