{extends file="main.phtml"}
{block name="left-area"}
<div class="portlet">
    <div class="portletFrame">
        <div class="portletHeader clearFix">
            <div class="portletHeaderFrame clearFix">
                <div class="title">
                    <a name="anchorf642"></a>
                    <span>财务管理</span>&nbsp;
                </div>
            </div>
        </div>
        <div class="portletContent">
            <ul class="article-list">
                <li class="article-list-item clearfix">
                    <a href="account.php">账户明细</a>
                </li>
                <li class="article-list-item clearfix">
                    <a href="reward.php">奖金查看</a>
                </li>
                <li class="article-list-item clearfix">
                    <a href="withdraw.php?act=add">提现申请</a>
                </li>
                <li class="article-list-item clearfix">
                    <a href="withdraw.php">提现记录</a>
                </li>
                <li class="article-list-item clearfix">
                    <a href="recharge.php?act=add">账户充值</a>
                </li>
                <li class="article-list-item clearfix">
                    <a href="recharge.php">充值记录</a>
                </li>
                <li class="article-list-item clearfix">
                    <a href="balance_transfer.php">余额转出</a>
                </li>
                <li class="article-list-item clearfix">
                    <a href="reward_transfer.php">奖金转出</a>
                </li>
            </ul>
        </div>
    </div>
</div>
{/block}
{block name="right-area"}
<div class="portlet">
    <div class="portletFrame">
        <div class="portletHeader clearFix">
            <div class="portletHeaderFrame clearFix">
                <div class="title">
                    <a name="anchorf642"></a>
                    <span>奖金转出</span>&nbsp;
                </div>
            </div>
        </div>
        <div class="portletContent">
            <p class="input-wrapper">
                <label class="input-label fl" for="">奖金余额：</label>
                <input type="text" class="input-text fl" value="{price_format($member_info.reward)}" readonly/>
            </p>
            <p class="input-wrapper">
                <label class="input-label fl" for="target">转入账号：</label>
                <input type="text" class="input-text fl" name="target" id="target"/>
            </p>
            <p class="input-wrapper">
                <label class="input-label fl" for="reward">转出金额：</label>
                <input type="text" class="input-text fl" name="reward" id="reward"/>
            </p>
            <p class="input-wrapper">
                <label class="input-label fl" for="password">二级密码：</label>
                <input type="password" class="input-text fl" name="password" id="password"/>
            </p>
            <p class="input-wrapper">
                <label class="input-label fl" for="remark">备注：</label>
                <input type="text" class="input-text fl" name="remark" id="remark"/>
            </p>
            <p class="input-wrapper">
                <label class="input-label fl">&nbsp;</label>
                <a class="input-btn" href="javascript:void(0);" id="submit-btn">
                    转出<img src="{$template_dir}images/btn_loading.gif" class="btn-loading-img"/>
                </a>
                <input type="hidden" name="opera" value="safe_login" />
            </p>
        </div>
        <script type="text/javascript">
            $(function() {
                $("#submit-btn").click(function () {
                    do_submit();
                });
            });

            var user_reward = {$member_info.reward};
            var flag = true;
            /**
             * 这个解决方案可以作为Ajax提交表单的模板
             * 1、form的提交操作托管给do_submit处理;
             * 2、Ajax操作分为两部分，第一部分do_submit作为提交前的参数验证，第二部分do_resposne作为返回代码的处理;
             * 3、仅支持post方式提交表单;
             * 4、需要在提交按钮加入提交中的加载图片，以及遮罩层代码;
             **/
            function do_submit() {
                //参数校验
                var msg = "";
                var password = $("#password").val().trim();
                var target = $("#target").val().trim();
                var reward = $("#reward").val().trim();
                var remark = $("#remark").val().trim();

                reward = parseFloat(reward);

                if(isNaN(reward) || reward <= 0) {
                    msg += "-请输入正确的转出金额\n";
                } else {
                    if(reward > user_reward) {
                        msg += "-奖金不足\n";
                    }
                }

                if(target == "") {
                    msg += "-请输入转入账号\n";
                }

                if(password == "") {
                    msg += "-请输入二级密码\n";
                }

                if(msg == "" && flag) {
                    //启用过渡效果
                    flag = false;
                    show_mask("submit-btn");

                    var params = { "opera":"reward_transfer", "password":password,  "remark":remark, "reward":reward, "target":target };
                    var url = "reward_transfer.php";
                    $.post(url, params, do_response, "json");
                    return true;
                }

                alert(msg);
                return false;
            }

            function do_response(result) {
                //关闭过渡效果
                flag = true;
                hide_mask("submit-btn");
                //处理返回结果
                if(result.error == 0) {
                    alert(result.msg);
                    //重置当前页面
                    window.location.reload();
                } else {
                    if(result.msg != "") {
                        alert(result.msg);
                    }
                    /*
                     if(result.errmsg.length) {
                     for(var id in result.errmsg) {
                     $("#"+id+"-error").text(result.errmsg[id]);
                     }
                     }
                     */
                }
            }
            /*----------------  Ajax end ---------------------*/
        </script>
    </div>
</div>
{/block}