{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}

<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="adminGroup-main">
        {if $act eq 'view'}
        <div class="article-main-header">
            <form action="" method="get" />
            <fieldset>
                <p>
                <div class="pull-left">
                    显示
                    <select name="count" class="w75">
                        <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                        <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                        <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                        <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                    </select>
                    项结果
                </div>
                <div class="pull-right">
                    <label>充值编号：</label>
                    <input class="text-input w150" type="text" id="small-input" name="recharge_sn" value="{$recharge_sn}">&nbsp;
                    <label>会员编号：</label>
                    <input class="text-input w150" type="text" id="small-input" name="account" value="{$account}">&nbsp;
                    <label>充值状态：</label>
                    <select name="status">
                        <option value="-1">全部</option>
                        <option value="1" {if $status eq 1}selected="selected"{/if}>待支付</option>
                        <option value="3" {if $status eq 3}selected="selected"{/if}>已支付</option>
                    </select><br/><br/>
                    <label>起止时间：</label>
                    <input class="text-input w150" type="text" id="begin_time" name="begin_time" value="{$begin_time}">&nbsp;
                    至
                    <input class="text-input w150" type="text" id="end_time" name="end_time" value="{$end_time}">&nbsp;
                    <button type="submit" class="btn btn-default">搜索</button>
                </div>
                </p>
            </fieldset>
            </form>
            <div class="clear"></div>
            <fieldset>
                <div class="pull-left">
                    <a class="btn btn-primary" href="javascript:order_export();">导出全部申请</a>
                    <a class="btn btn-primary" href="javascript:order_selected_export();">导出选中申请</a>
                </div>
                <div class="clear"></div>
            </fieldset>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th><a href="javascript:select_all();">全选</a>/<a href="javascript:deselect();">反选</a></th>
                <th>充值编号</th>
                <th>会员账号</th>
                <th>充值金额</th>
                <th>备注</th>
                <th>状态</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$recharge_list item=recharge}
            <tr>
                <td><input type="checkbox" name="id[]" value="{$recharge.id}"/></td>
                <td>{$recharge.recharge_sn}</td>
                <td>{$recharge.account}</td>
                <td>{$recharge.real_amount}</td>
                <td>{$recharge.remark}</td>
                <td>{$lang.recharge["status_{$recharge.status}"]}</td>
                <td>
                    {$recharge.operation}
                </td>
            </tr>
            {/foreach}
            <tr>
                <td colspan="7">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&keyword={$keyword}&count={$count}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&keyword={$keyword}&count={$count}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&keyword={$keyword}&count={$count}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&keyword={$keyword}&count={$count}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&keyword={$keyword}&count={$count}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
        <script type="text/javascript" src="laydate/laydate.js"></script>
        <script type="text/javascript">
            var start = {
                elem: '#begin_time',
                format: 'yyyy-MM-dd',
                max: '9999-12-31 23:59:59', //最大日期
                istime: false,
                istoday: true,
                choose: function(datas){
                    end.min = datas; //开始日选好后，重置结束日的最小日期
                    end.start = datas //将结束日的初始值设定为开始日
                    end.click;
                }
            };

            var end = {
                elem: '#end_time',
                format: 'yyyy-MM-dd',
                max: '9999-12-31 23:59:59',
                istime: false,
                istoday: true,
                choose: function(datas){
                    start.max = datas; //结束日选好后，重置开始日的最大日期
                }
            };

            laydate.render(start);
            laydate.render(end);
        </script>
        <script type="text/javascript">
            function order_export() {
                var form = $("<form>");
                form.attr({
                    "style":"display:none;",
                    "method": "post",
                    "action": window.location.href
                });

                var input = $("<input>");
                input.attr({
                    "type": "hidden",
                    "name": "opera",
                    "value": "export"
                });

                form.append(input);
                $("html").append(form);
                form.submit();
            }

            function order_selected_export() {
                var order_id = "";

                $("input[name='id[]']").each(function(i, e){
                    if(e.checked) {
                        order_id += e.value+",";
                    }
                });

                if(order_id == "") return false;

                var form = $("<form>");
                form.attr({
                    "style":"display:none;",
                    "method": "post",
                    "action": window.location.href
                });

                var input = $("<input>");
                input.attr({
                    "type": "hidden",
                    "name": "opera",
                    "value": "export"
                });

                form.append(input);

                var input = $("<input>");
                input.attr({
                    "type": "hidden",
                    "name": "recharge_id",
                    "value": order_id
                });

                form.append(input);

                $("html").append(form);
                form.submit();
            }

            function select_all() {
                $("input[name='id[]']").each(function(i, e){
                    e.checked = true;
                });
            }

            function deselect() {
                $("input[name='id[]']").each(function(i, e){
                    if(e.checked) {
                        e.checked = false;
                    } else {
                        e.checked = true;
                    }
                });
            }
        </script>
        {/if}

        <!-- 充值处理 -->
        {if $act eq 'edit'}
        <form method="post">
            <fieldset>
                <p>
                    <label class="l-title">会员账号：</label>
                    {$recharge.account}
                </p>
                <p>
                    <label class="l-title">充值金额：</label>
                    {$recharge.real_amount}
                </p>
                <p>
                    <label class="l-title">备注：</label>
                    {str_replace('<br/>', ' ', $recharge.remark)}
                </p>
                <p>
                    <label class="l-title">汇入账户：</label>
                    {str_replace('<br/>', "\n", $recharge.payment_name)}
                </p>
                <p>
                    <label class="l-title">备注：</label>
                    <input class="text-input w300" type="text" id="remark" name="remark" placeholder="请输入备注" value="">
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="edit"/>
                    <input type="hidden" name="erecharge_sn" value="{$recharge.recharge_sn}">
                    <button class="btn btn-primary" type="submit">设为已处理</button> &nbsp;<a href="recharge.php" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
        {/if}
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>